import Rigid.AffinoidSpectrum.RationalBasis

set_option linter.style.header false

/-!
# Rational and Laurent covers

This file supplies the finite-cover objects used in Tate's acyclicity argument and constructs the
two-member Laurent cover associated with one analytic function.
-/

universe u v

namespace Rigid

variable (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable (A : Type v) [NormedCommRing A] [NormedAlgebra K A] [CompleteSpace A]
  [IsUltrametricDist A]

namespace AffinoidRationalSubdomain

/-- The whole affinoid spectrum, represented as a rational subdomain with no numerators. -/
noncomputable def whole : AffinoidRationalSubdomain K A where
  n := 0
  g := 1
  f := Fin.elim0
  isRational := by
    rw [IsRationalDatum]
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    exact Set.mem_insert 1 _

@[simp]
theorem carrier_whole : (whole K A).carrier = Set.univ := by
  ext x
  simp [whole, carrier, BerkovichSpectrumOver.rationalDomainSet]

/-- The Laurent subdomain on which `|f| ≤ 1`. -/
noncomputable def laurentLE (f : A) : AffinoidRationalSubdomain K A where
  n := 1
  g := 1
  f := fun _ ↦ f
  isRational := by
    rw [IsRationalDatum]
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    exact Set.mem_insert 1 _

/-- The Laurent subdomain on which `1 ≤ |f|`. -/
noncomputable def laurentGE (f : A) : AffinoidRationalSubdomain K A where
  n := 1
  g := f
  f := fun _ ↦ 1
  isRational := by
    rw [IsRationalDatum]
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    exact Set.mem_insert_of_mem f ⟨0, rfl⟩

@[simp]
theorem mem_carrier_laurentLE (f : A) (x : BerkovichSpectrumOver K A) :
    x ∈ (laurentLE K A f).carrier ↔ x f ≤ 1 := by
  simp [laurentLE, carrier, BerkovichSpectrumOver.rationalDomainSet]

@[simp]
theorem mem_carrier_laurentGE (f : A) (x : BerkovichSpectrumOver K A) :
    x ∈ (laurentGE K A f).carrier ↔ 1 ≤ x f := by
  simp [laurentGE, carrier, BerkovichSpectrumOver.rationalDomainSet]

/-- A finite rational cover of a rational subdomain. -/
structure Cover (U : AffinoidRationalSubdomain K A) where
  m : ℕ
  domain : Fin m → AffinoidRationalSubdomain K A
  subset : ∀ i, (domain i).carrier ⊆ U.carrier
  covers : U.carrier = ⋃ i, (domain i).carrier

namespace Cover

/-- `𝒱` refines `𝒰` when every member of `𝒱` is contained in a specified member of
`𝒰`. -/
structure Refinement {U : AffinoidRationalSubdomain K A} (𝒱 𝒰 : Cover K A U) where
  index : Fin 𝒱.m → Fin 𝒰.m
  subset : ∀ j, (𝒱.domain j).carrier ⊆ (𝒰.domain (index j)).carrier

/-- Every rational cover refines itself. -/
def Refinement.refl {U : AffinoidRationalSubdomain K A} (𝒰 : Cover K A U) :
    Refinement K A 𝒰 𝒰 where
  index := id
  subset := fun _ ↦ Set.Subset.rfl

/-- Refinements compose. -/
def Refinement.trans {U : AffinoidRationalSubdomain K A} {𝒲 𝒱 𝒰 : Cover K A U}
    (h𝒲𝒱 : Refinement K A 𝒲 𝒱) (h𝒱𝒰 : Refinement K A 𝒱 𝒰) :
    Refinement K A 𝒲 𝒰 where
  index := h𝒱𝒰.index ∘ h𝒲𝒱.index
  subset := fun j ↦ (h𝒲𝒱.subset j).trans (h𝒱𝒰.subset (h𝒲𝒱.index j))

/-- The two-member Laurent cover `|f| ≤ 1` and `1 ≤ |f|` of the whole spectrum. -/
noncomputable def laurent (f : A) : Cover K A (whole K A) where
  m := 2
  domain := ![laurentLE K A f, laurentGE K A f]
  subset := fun _ ↦ by rw [carrier_whole]; exact Set.subset_univ _
  covers := by
    rw [carrier_whole]
    symm
    apply Set.eq_univ_of_forall
    intro x
    by_cases hx : x f ≤ 1
    · apply Set.mem_iUnion.mpr
      refine ⟨0, ?_⟩
      simpa [Fin.cases] using hx
    · apply Set.mem_iUnion.mpr
      refine ⟨1, ?_⟩
      have hx' : 1 ≤ x f := (le_total 1 (x f)).resolve_right hx
      simpa [Fin.cases] using hx'

/-- The member with denominator `qᵢ` of the rational cover generated by a unit-ideal
family `q`. -/
noncomputable def generatedDomain {r : ℕ} (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (i : Fin r) : AffinoidRationalSubdomain K A where
  n := r
  g := q i
  f := q
  isRational := by
    apply top_unique
    rw [← hq]
    exact Ideal.span_mono (Set.subset_insert (q i) (Set.range q))

@[simp]
theorem mem_generatedDomain_carrier {r : ℕ} (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (i : Fin r) (x : BerkovichSpectrumOver K A) :
    x ∈ (generatedDomain K A q hq i).carrier ↔ ∀ j, x (q j) ≤ x (q i) := by
  rfl

/-- A finite family generating the unit ideal gives its standard rational cover: at every point,
choose an index at which the family has maximal modulus. -/
noncomputable def generated {r : ℕ} (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) : Cover K A (whole K A) where
  m := r
  domain := generatedDomain K A q hq
  subset := fun _ ↦ by rw [carrier_whole]; exact Set.subset_univ _
  covers := by
    rcases eq_or_ne r 0 with hr | hr
    · subst r
      rw [carrier_whole]
      simp only [Set.iUnion_of_empty]
      ext x
      simp only [Set.mem_univ, Set.mem_empty_iff_false, iff_false]
      intro _
      have hbot : (⊥ : Ideal A) = ⊤ := by simpa using hq
      have hone : (1 : A) ∈ (⊥ : Ideal A) := by rw [hbot]; simp
      have h10 : (1 : A) = 0 := by simpa using hone
      have hx := congrArg (fun a : A ↦ x a) h10
      rw [BerkovichSpectrumOver.map_one, BerkovichSpectrumOver.map_zero] at hx
      exact one_ne_zero hx
    · letI : Nonempty (Fin r) := Fin.pos_iff_nonempty.mp (Nat.pos_of_ne_zero hr)
      rw [carrier_whole]
      symm
      apply Set.eq_univ_of_forall
      intro x
      obtain ⟨i, hi⟩ := Finite.exists_max (fun i : Fin r ↦ x (q i))
      apply Set.mem_iUnion.mpr
      exact ⟨i, (mem_generatedDomain_carrier K A q hq i x).2 hi⟩

end Cover

end AffinoidRationalSubdomain

end Rigid
