import Mathlib.CategoryTheory.Limits.Shapes.Pullback.HasPullback
import Mathlib.CategoryTheory.Sites.Pretopology

set_option linter.style.header false
set_option linter.checkUnivs false

/-!
# Admissible sites

This file packages the point-set presentation of a G-topology as a small category of admissible
opens, with inclusions as morphisms, together with a mathlib `Pretopology`.  The associated
Grothendieck topology is always obtained using `Pretopology.toGrothendieck`.

The extra condition `precover_covers` records that the covering presieves really are
set-theoretic covers.  It is not another version of the Grothendieck-topology axioms.
-/

open CategoryTheory
open CategoryTheory.Limits

universe p o

namespace Rigid

/-- A small family of subsets, closed under the whole set and binary intersections.

The order is inclusion of carriers. In particular, admissible opens are determined by their
underlying point sets, as in the definition of a G-topology. -/
structure AdmissibleBasis where
  Point : Type p
  Open : Type o
  [openPartialOrder : PartialOrder Open]
  [openHasPullbacks : HasPullbacks Open]
  carrier : Open → Set Point
  le_iff : ∀ {U V}, U ≤ V ↔ carrier U ⊆ carrier V
  top : Open
  carrier_top : carrier top = Set.univ
  inter : Open → Open → Open
  carrier_inter : ∀ U V, carrier (inter U V) = carrier U ∩ carrier V

attribute [instance] AdmissibleBasis.openPartialOrder AdmissibleBasis.openHasPullbacks

namespace AdmissibleBasis

variable (B : AdmissibleBasis.{p, o})

theorem carrier_mono {U V : B.Open} (h : U ≤ V) : B.carrier U ⊆ B.carrier V :=
  B.le_iff.mp h

theorem carrier_injective : Function.Injective B.carrier := by
  intro U V h
  apply le_antisymm
  · exact B.le_iff.mpr h.le
  · exact B.le_iff.mpr h.ge

theorem top_mem (x : B.Point) : x ∈ B.carrier B.top := by
  rw [B.carrier_top]
  exact Set.mem_univ x

theorem inter_le_left (U V : B.Open) : B.inter U V ≤ U := by
  rw [B.le_iff, B.carrier_inter]
  exact Set.inter_subset_left

theorem inter_le_right (U V : B.Open) : B.inter U V ≤ V := by
  rw [B.le_iff, B.carrier_inter]
  exact Set.inter_subset_right

theorem le_inter {T U V : B.Open} (hU : T ≤ U) (hV : T ≤ V) : T ≤ B.inter U V := by
  rw [B.le_iff, B.carrier_inter]
  exact fun x hx ↦ ⟨B.carrier_mono hU hx, B.carrier_mono hV hx⟩

/-- In the inclusion category of a G-basis, intersections are pullbacks. -/
def interPullbackCone {U V W : B.Open} (f : U ⟶ W) (g : V ⟶ W) :
    PullbackCone f g :=
  PullbackCone.mk (homOfLE (B.inter_le_left U V)) (homOfLE (B.inter_le_right U V))
    (Subsingleton.elim _ _)

/-- The intersection cone has the universal property of the pullback. -/
def interPullbackConeIsLimit {U V W : B.Open} (f : U ⟶ W) (g : V ⟶ W) :
    IsLimit (B.interPullbackCone f g) :=
  PullbackCone.IsLimit.mk _
    (fun s ↦ homOfLE (B.le_inter (leOfHom s.fst) (leOfHom s.snd)))
    (fun _ ↦ Subsingleton.elim _ _) (fun _ ↦ Subsingleton.elim _ _)
    (fun _ _ _ _ ↦ Subsingleton.elim _ _)

/-- The canonical pullback instance supplied by intersections.  Constructors of an
`AdmissibleBasis` can use this as their `openHasPullbacks` field. -/
theorem hasPullbackOfInter {U V W : B.Open} (f : U ⟶ W) (g : V ⟶ W) :
    HasPullback f g where
  exists_limit := ⟨⟨B.interPullbackCone f g, B.interPullbackConeIsLimit f g⟩⟩

end AdmissibleBasis

/-- A G-site: an admissible basis, a pretopology on it, and the assertion that pretopology
coverings cover the underlying point set. -/
structure AdmissibleSite extends AdmissibleBasis.{p, o} where
  pretopology : Pretopology toAdmissibleBasis.Open
  precover_covers :
    ∀ {U : toAdmissibleBasis.Open} {R : Presieve U}, R ∈ pretopology U →
      ∀ x ∈ toAdmissibleBasis.carrier U,
        ∃ (V : toAdmissibleBasis.Open) (f : V ⟶ U),
          R f ∧ x ∈ toAdmissibleBasis.carrier V

namespace AdmissibleSite

variable (X : Rigid.AdmissibleSite.{p, o})

/-- The Grothendieck topology generated by the admissible pretopology. -/
def topology : GrothendieckTopology X.Open :=
  X.pretopology.toGrothendieck

/-- A covering sieve in the generated topology covers the underlying point set. -/
theorem coveringSieve_covers {U : X.Open} {S : Sieve U} (hS : S ∈ X.topology U)
    {x : X.Point} (hx : x ∈ X.carrier U) :
    ∃ (V : X.Open) (f : V ⟶ U), S f ∧ x ∈ X.carrier V := by
  rcases hS with ⟨R, hR, hRS⟩
  obtain ⟨V, f, hf, hxV⟩ := X.precover_covers hR x hx
  exact ⟨V, f, hRS V f hf, hxV⟩

/-- The presieve associated to an indexed family of inclusions. -/
def familyPresieve {ι : Type*} {U : ι → X.Open} {V : X.Open}
    (hUV : ∀ i, U i ≤ V) : Presieve V :=
  Presieve.ofArrows U (fun i ↦ homOfLE (hUV i))

/-- An indexed family is an admissible cover when its generated sieve is covering. -/
def IsCover {ι : Type*} (U : ι → X.Open) (V : X.Open) : Prop :=
  ∃ hUV : ∀ i, U i ≤ V, Sieve.generate (X.familyPresieve hUV) ∈ X.topology V

namespace IsCover

variable {X}

/-- Every member of an admissible cover is contained in the covered open. -/
theorem subset {ι : Type*} {U : ι → X.Open} {V : X.Open} (h : X.IsCover U V)
    (i : ι) : U i ≤ V :=
  h.choose i

/-- A family admitting a covering refinement is itself an admissible cover. This is the
Grothendieck-topology form of the saturation axiom for coverings. -/
theorem of_refinement {ι κ : Type*} {U : ι → X.Open} {W : κ → X.Open} {V : X.Open}
    (hUV : ∀ i, U i ≤ V) (hW : X.IsCover W V) (r : κ → ι)
    (hr : ∀ j, W j ≤ U (r j)) : X.IsCover U V := by
  rcases hW with ⟨_, hWcover⟩
  refine ⟨hUV, X.topology.superset_covering ?_ hWcover⟩
  intro T q hq
  rcases hq with ⟨Z, a, b, ⟨j⟩, hab⟩
  refine
    ⟨U (r j), a ≫ homOfLE (hr j), homOfLE (hUV (r j)), ⟨r j⟩, Subsingleton.elim _ _⟩

/-- The singleton family is an admissible cover. -/
theorem singleton (V : X.Open) : X.IsCover (fun _ : PUnit ↦ V) V := by
  refine ⟨fun _ ↦ le_rfl, ?_⟩
  simp [AdmissibleSite.familyPresieve, Presieve.ofArrows_pUnit]

/-- Admissible covers are stable under intersection with another admissible open. -/
theorem pullback {ι : Type*} {U : ι → X.Open} {V : X.Open} (h : X.IsCover U V)
    (W : X.Open) :
    X.IsCover (fun i ↦ X.inter (U i) W) (X.inter V W) := by
  rcases h with ⟨hUV, hcover⟩
  let p : X.inter V W ⟶ V := homOfLE (X.toAdmissibleBasis.inter_le_left V W)
  let hIW : ∀ i, X.inter (U i) W ≤ X.inter V W := fun i ↦
    X.toAdmissibleBasis.le_inter
      ((X.toAdmissibleBasis.inter_le_left (U i) W).trans (hUV i))
      (X.toAdmissibleBasis.inter_le_right (U i) W)
  refine ⟨hIW, X.topology.superset_covering ?_ (X.topology.pullback_stable p hcover)⟩
  rintro T q hq
  change Sieve.generate (X.familyPresieve hUV) (q ≫ p) at hq
  rcases hq with ⟨Z, a, b, ⟨i⟩, hab⟩
  refine ⟨X.inter (U i) W, homOfLE ?_, homOfLE (hIW i), ⟨i⟩, Subsingleton.elim _ _⟩
  apply X.toAdmissibleBasis.le_inter
  · exact leOfHom a
  · exact (leOfHom q).trans (X.toAdmissibleBasis.inter_le_right V W)

/-- Admissible coverings are transitive. -/
theorem trans {ι : Type*} {κ : ι → Type*} {U : ι → X.Open} {V : X.Open}
    (hU : X.IsCover U V) (W : ∀ i, κ i → X.Open)
    (hW : ∀ i, X.IsCover (W i) (U i)) :
    X.IsCover (fun p : Σ i, κ i ↦ W p.1 p.2) V := by
  rcases hU with ⟨hUV, hUcover⟩
  choose hWU hWcover using hW
  let f : ∀ i, U i ⟶ V := fun i ↦ homOfLE (hUV i)
  let g : ∀ i j, W i j ⟶ U i := fun i j ↦ homOfLE (hWU i j)
  refine ⟨fun p ↦ (hWU p.1 p.2).trans (hUV p.1), ?_⟩
  have hbind := X.topology.bindOfArrows (f := f) (R := fun i ↦ X.familyPresieve (hWU i))
    hUcover hWcover
  change Sieve.generate
    (Presieve.bindOfArrows U f (fun i ↦ Presieve.ofArrows (W i) (g i))) ∈
      X.topology V at hbind
  rw [Presieve.bindOfArrows_ofArrows f g] at hbind
  convert hbind using 1
  apply Sieve.ext
  intro T q
  rfl

/-- The carriers of an admissible covering family have union equal to the covered carrier. -/
theorem iUnion_carrier {ι : Type*} {U : ι → X.Open} {V : X.Open}
    (h : X.IsCover U V) : X.carrier V = ⋃ i, X.carrier (U i) := by
  apply Set.Subset.antisymm
  · intro x hx
    rcases h with ⟨hUV, hcover⟩
    obtain ⟨T, q, hq, hxT⟩ := X.coveringSieve_covers hcover hx
    rcases hq with ⟨Z, a, b, ⟨i⟩, hab⟩
    exact Set.mem_iUnion.mpr ⟨i, X.toAdmissibleBasis.carrier_mono (leOfHom a) hxT⟩
  · intro x hx
    rcases Set.mem_iUnion.mp hx with ⟨i, hxi⟩
    exact X.toAdmissibleBasis.carrier_mono (h.subset i) hxi

end IsCover

/-- A quasi-compact admissible open is one for which every admissible cover has a finite
admissible subcover.  This is deliberately separate from admissibility itself. -/
def IsQuasiCompact (U : X.Open) : Prop :=
  ∀ {ι : Type*} (V : ι → X.Open), X.IsCover V U →
    ∃ s : Set ι, s.Finite ∧ X.IsCover (fun i : s ↦ V i.1) U

end AdmissibleSite

end Rigid
