import Mathlib.Algebra.Category.CommAlgCat.Basic
import Mathlib.CategoryTheory.Filtered.Basic
import Mathlib.CategoryTheory.Sites.Sheaf
import Rigid.RigidSpace.AdmissibleSite

set_option linter.style.header false

/-!
# G-ringed and G-locally ringed spaces

The structure sheaf is a mathlib `Sheaf` on the Grothendieck topology generated by the admissible
pretopology.  Sections and restriction maps are evaluations of that sheaf.  Stalks are filtered
colimits over admissible neighbourhoods, and germs are the canonical colimit maps.
-/

open CategoryTheory
open CategoryTheory.Limits

universe k

namespace Rigid

variable (K : Type k) [CommRing K]

/-- A G-ringed space over `K`. -/
structure GRingedSpace where
  toAdmissibleSite : AdmissibleSite.{k, k}
  structureSheaf :
    Sheaf toAdmissibleSite.topology (CommAlgCat.{k} K)

namespace GRingedSpace

variable (X : GRingedSpace.{k} K)

/-- Analytic functions on an admissible open. -/
abbrev Sections (U : X.toAdmissibleSite.Open) : Type k :=
  X.structureSheaf.obj.obj (Opposite.op U)

/-- Restriction of analytic functions along an inclusion of admissible opens. -/
def restriction {U V : X.toAdmissibleSite.Open} (hUV : U ≤ V) :
    Sections K X V →ₐ[K] Sections K X U :=
  (X.structureSheaf.obj.map (homOfLE hUV).op).hom

@[simp]
theorem restriction_id (U : X.toAdmissibleSite.Open) :
    restriction K X (U := U) (V := U) le_rfl = AlgHom.id K (Sections K X U) := by
  change (X.structureSheaf.obj.map (𝟙 (Opposite.op U))).hom = _
  rw [X.structureSheaf.obj.map_id]
  rfl

@[simp]
theorem restriction_comp {U V W : X.toAdmissibleSite.Open} (hUV : U ≤ V) (hWU : W ≤ U) :
    (restriction K X hWU).comp (restriction K X hUV) =
      restriction K X (hWU.trans hUV) := by
  change
    (X.structureSheaf.obj.map (homOfLE hUV).op ≫
      X.structureSheaf.obj.map (homOfLE hWU).op).hom =
        (X.structureSheaf.obj.map (homOfLE (hWU.trans hUV)).op).hom
  rw [← X.structureSheaf.obj.map_comp]
  rfl

/-- The representable form of the sheaf condition for an indexed admissible cover.  This is the
categorical sheaf condition used by mathlib for a `CommAlgCat`-valued sheaf. -/
theorem isSheafFor_isCover (E : CommAlgCat.{k} K) {ι : Type*}
    {U : ι → X.toAdmissibleSite.Open}
    {V : X.toAdmissibleSite.Open} (h : X.toAdmissibleSite.IsCover U V) :
    Presieve.IsSheafFor
      (X.structureSheaf.obj ⋙ coyoneda.obj (Opposite.op E))
      (X.toAdmissibleSite.familyPresieve h.choose) := by
  rw [Presieve.isSheafFor_iff_generate]
  exact X.structureSheaf.property E _ h.choose_spec

/-- An admissible neighbourhood of a point.  Its order is reverse inclusion, so restriction maps
form a direct system. -/
structure Neighborhood (x : X.toAdmissibleSite.Point) where
  obj : X.toAdmissibleSite.Open
  mem : x ∈ X.toAdmissibleSite.carrier obj

namespace Neighborhood

variable {X} {x : X.toAdmissibleSite.Point}

instance : Preorder (Neighborhood K X x) where
  le U V := V.obj ≤ U.obj
  le_refl _ := le_rfl
  le_trans _ _ _ hUV hVW := hVW.trans hUV

/-- The full admissible open is a neighbourhood of every point. -/
def top : Neighborhood K X x where
  obj := X.toAdmissibleSite.top
  mem := X.toAdmissibleSite.toAdmissibleBasis.top_mem x

/-- Intersections give common refinements of admissible neighbourhoods. -/
def inter (U V : Neighborhood K X x) : Neighborhood K X x where
  obj := X.toAdmissibleSite.inter U.obj V.obj
  mem := by
    rw [X.toAdmissibleSite.carrier_inter]
    exact ⟨U.mem, V.mem⟩

instance : Nonempty (Neighborhood K X x) :=
  ⟨top (K := K)⟩

instance : IsFiltered (Neighborhood K X x) where
  cocone_objs U V :=
    ⟨inter (K := K) U V,
      homOfLE (X.toAdmissibleSite.toAdmissibleBasis.inter_le_left U.obj V.obj),
      homOfLE (X.toAdmissibleSite.toAdmissibleBasis.inter_le_right U.obj V.obj), trivial⟩
  cocone_maps := fun {_ _} _ _ ↦ ⟨_, 𝟙 _, Subsingleton.elim _ _⟩

end Neighborhood

/-- The direct system of section algebras over admissible neighbourhoods. -/
@[reducible]
def stalkDiagram (x : X.toAdmissibleSite.Point) :
    Neighborhood K X x ⥤ CommAlgCat.{k} K where
  obj U := X.structureSheaf.obj.obj (Opposite.op U.obj)
  map {U V} f :=
    X.structureSheaf.obj.map
      (homOfLE (show V.obj ≤ U.obj from leOfHom f)).op
  map_id U := by
    change X.structureSheaf.obj.map (𝟙 (Opposite.op U.obj)) = 𝟙 _
    exact X.structureSheaf.obj.map_id _
  map_comp f g := by
    rw [← X.structureSheaf.obj.map_comp]
    rfl

/-- The stalk object is the filtered colimit over admissible neighbourhoods. -/
noncomputable abbrev stalkObj (x : X.toAdmissibleSite.Point) : CommAlgCat.{k} K :=
  colimit (stalkDiagram K X x)

/-- The local ring of germs at a point, as an underlying type. -/
noncomputable abbrev Stalk (x : X.toAdmissibleSite.Point) : Type k :=
  stalkObj K X x

/-- The germ map is the canonical map into the neighbourhood colimit. -/
noncomputable def germ {U : X.toAdmissibleSite.Open} {x : X.toAdmissibleSite.Point}
    (hx : x ∈ X.toAdmissibleSite.carrier U) :
    Sections K X U →ₐ[K] Stalk K X x :=
  (colimit.ι (stalkDiagram K X x) ⟨U, hx⟩).hom

/-- Germs commute with restriction. -/
@[simp]
theorem germ_restriction {U V : X.toAdmissibleSite.Open} (hUV : U ≤ V)
    {x : X.toAdmissibleSite.Point} (hx : x ∈ X.toAdmissibleSite.carrier U) :
    (germ K X hx).comp (restriction K X hUV) =
      germ K X (X.toAdmissibleSite.toAdmissibleBasis.carrier_mono hUV hx) := by
  let V' : Neighborhood K X x :=
    ⟨V, X.toAdmissibleSite.toAdmissibleBasis.carrier_mono hUV hx⟩
  let U' : Neighborhood K X x := ⟨U, hx⟩
  let f : V' ⟶ U' := homOfLE hUV
  have hw := colimit.w (stalkDiagram K X x) f
  exact congrArg CommAlgCat.Hom.hom hw

end GRingedSpace

/-- A G-locally ringed space is a G-ringed space whose canonically constructed stalks are local
rings. -/
structure LocallyGRingedSpace extends GRingedSpace.{k} K where
  stalk_isLocal :
    ∀ x : toGRingedSpace.toAdmissibleSite.Point,
      IsLocalRing (GRingedSpace.Stalk K toGRingedSpace x)

namespace LocallyGRingedSpace

variable (X : LocallyGRingedSpace.{k} K)

instance stalkIsLocal (x : X.toAdmissibleSite.Point) :
    IsLocalRing (GRingedSpace.Stalk K X.toGRingedSpace x) :=
  X.stalk_isLocal x

end LocallyGRingedSpace

end Rigid
