import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.LinearAlgebra.Basis.VectorSpace

set_option linter.style.header false

/-!
# Linear functionals on simple field extensions

The domain case of Proposition 4.5.3 extends evaluation at a root from the simple field generated
by an element to the ambient fraction field.  This file isolates that purely linear-algebraic
step.  No finiteness assumption is needed for existence; finite generation is used later to prove
that the resulting functional is bounded.
-/

namespace Rigid

namespace FiniteExtensionFunctional

universe u v w

variable {F : Type u} {E : Type v} {L : Type w}
variable [Field F] [Field E] [Field L] [Algebra F E] [Algebra F L]

/-- Evaluation at a root of the minimal polynomial, transported to the simple field generated by
the original algebraic element. -/
noncomputable def adjoinSimpleLift (c : E) (hc : IsIntegral F c) (z : L)
    (hz : Polynomial.aeval z (minpoly F c) = 0) :
    IntermediateField.adjoin F {c} →ₐ[F] L :=
  (AdjoinRoot.liftAlgHom (minpoly F c) (Algebra.ofId F L) z hz).comp
    (IntermediateField.adjoinRootEquivAdjoin F hc).symm.toAlgHom

@[simp]
theorem adjoinSimpleLift_gen (c : E) (hc : IsIntegral F c) (z : L)
    (hz : Polynomial.aeval z (minpoly F c) = 0) :
    adjoinSimpleLift c hc z hz (IntermediateField.AdjoinSimple.gen F c) = z := by
  change Polynomial.eval₂ (Algebra.ofId F L) z (minpoly F c) = 0 at hz
  simp [adjoinSimpleLift, IntermediateField.adjoinRootEquivAdjoin_symm_apply_gen]

/-- An `F`-algebra map from the simple field `F(c)` extends to an `F`-linear map on `E`, and the
extension carries every power of `c` to the corresponding power of the image of the generator.

This is the linear-extension step in the proof of Proposition 4.5.7. -/
theorem exists_linearMap_map_pow_eq (c : E)
    (g : IntermediateField.adjoin F {c} →ₐ[F] L) :
    ∃ G : E →ₗ[F] L, ∀ m : ℕ, G (c ^ m) = g (IntermediateField.AdjoinSimple.gen F c) ^ m := by
  obtain ⟨G, hG⟩ := LinearMap.exists_extend (K := F) (V := E) (V' := L)
    (p := (IntermediateField.adjoin F {c}).toSubmodule) g.toLinearMap
  refine ⟨G, fun m ↦ ?_⟩
  let cm : IntermediateField.adjoin F {c} :=
    (IntermediateField.AdjoinSimple.gen F c) ^ m
  have hm := LinearMap.congr_fun hG cm
  change G (c ^ m) = g cm at hm
  calc
    G (c ^ m) = g cm := hm
    _ = g (IntermediateField.AdjoinSimple.gen F c) ^ m := map_pow g _ m

/-- A root of the minimal polynomial gives a linear functional on the ambient field carrying all
powers of the original element to the corresponding powers of that root. -/
theorem exists_linearMap_map_pow_eq_of_minpoly_root (c : E) (hc : IsIntegral F c) (z : L)
    (hz : Polynomial.aeval z (minpoly F c) = 0) :
    ∃ G : E →ₗ[F] L, ∀ m : ℕ, G (c ^ m) = z ^ m := by
  obtain ⟨G, hG⟩ := exists_linearMap_map_pow_eq c (adjoinSimpleLift c hc z hz)
  refine ⟨G, fun m ↦ ?_⟩
  simpa using hG m

section Restriction

variable {R : Type*} {C : Type*}
variable [CommRing R] [CommRing C] [Algebra R C]
variable [Algebra R F] [Algebra R E] [Algebra R L]
variable [Algebra C E]
variable [IsScalarTower R C E] [IsScalarTower R F E] [IsScalarTower R F L]

/-- Restrict the extended functional from a field containing `C` back to `C`.  In the application,
`F` and `E` are fraction fields of `R` and `C`, respectively. -/
theorem exists_linearMap_map_algebraMap_pow_eq (c : C)
    (g : IntermediateField.adjoin F {algebraMap C E c} →ₐ[F] L) :
    ∃ G : C →ₗ[R] L, ∀ m : ℕ,
      G (c ^ m) = g (IntermediateField.AdjoinSimple.gen F (algebraMap C E c)) ^ m := by
  obtain ⟨H, hH⟩ := exists_linearMap_map_pow_eq (F := F) (E := E) (L := L)
    (algebraMap C E c) g
  let i : C →ₗ[R] E := (IsScalarTower.toAlgHom R C E).toLinearMap
  let G : C →ₗ[R] L := (H.restrictScalars R).comp i
  refine ⟨G, fun m ↦ ?_⟩
  change H (algebraMap C E (c ^ m)) = _
  rw [map_pow]
  exact hH m

/-- Restrict the minimal-polynomial root functional to the original finite algebra. -/
theorem exists_linearMap_map_algebraMap_pow_eq_of_minpoly_root (c : C)
    (hc : IsIntegral F (algebraMap C E c)) (z : L)
    (hz : Polynomial.aeval z (minpoly F (algebraMap C E c)) = 0) :
    ∃ G : C →ₗ[R] L, ∀ m : ℕ, G (c ^ m) = z ^ m := by
  obtain ⟨G, hG⟩ := exists_linearMap_map_algebraMap_pow_eq (R := R) (F := F) (E := E)
    (L := L) c (adjoinSimpleLift (algebraMap C E c) hc z hz)
  refine ⟨G, fun m ↦ ?_⟩
  simpa using hG m

end Restriction

end FiniteExtensionFunctional

end Rigid
