import Rigid.AffinoidAlgebra.Basic
import Rigid.AffinoidAlgebra.NoetherNormalization
import Rigid.AffinoidAlgebra.RationalDatum
import Rigid.AffinoidAlgebra.RelativeTate
import Rigid.TateAlgebra.RelativeUniversalProperty
import Mathlib.Analysis.Normed.Group.Quotient
import Mathlib.RingTheory.Ideal.Span

set_option linter.style.header false
set_option linter.unusedSectionVars false

/-!
# Rational localizations

The rational localization attached to `g, f₁, ..., fₙ` is the quotient Banach algebra
`A⟨T₁, ..., Tₙ⟩ / (gTᵢ - fᵢ)`.  We take the closure of the relation ideal so that the quotient is
separated and complete.  The relative Tate universal property shows that this quotient has the
expected mapping property for power-bounded coordinate images.
-/

open scoped Topology

universe u v w

namespace Rigid

variable (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable (A : Type v) [NormedCommRing A] [NormedAlgebra K A] [CompleteSpace A]
  [IsUltrametricDist A]

/-- The closed ideal generated by the rational-localization relations. -/
noncomputable def rationalLocalizationIdeal (n : ℕ) (g : A) (f : Fin n → A) :
    Ideal (TateAlgebra A (Fin n)) :=
  (Ideal.span (Set.range fun i ↦
    TateAlgebra.C A (Fin n) g * tateVariable A (Fin n) i - TateAlgebra.C A (Fin n) (f i))).closure

noncomputable instance rationalLocalizationIdealIsClosed (n : ℕ) (g : A) (f : Fin n → A) :
    IsClosed ((rationalLocalizationIdeal A n g f : Ideal (TateAlgebra A (Fin n))) :
      Set (TateAlgebra A (Fin n))) := by
  unfold rationalLocalizationIdeal
  exact isClosed_closure

/-- The Banach algebra `A⟨T₁, ..., Tₙ⟩ / (gTᵢ - fᵢ)`. -/
abbrev RationalLocalization
    (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
    (A : Type v) [NormedCommRing A] [NormedAlgebra K A] [CompleteSpace A]
    [IsUltrametricDist A] (n : ℕ) (g : A) (f : Fin n → A) : Type v :=
  TateAlgebra A (Fin n) ⧸ rationalLocalizationIdeal A n g f

@[reducible] noncomputable instance (priority := 100) rationalLocalizationNormedCommRing
    (n : ℕ) (g : A) (f : Fin n → A) :
    NormedCommRing (RationalLocalization K A n g f) := by
  letI : IsClosed ((rationalLocalizationIdeal A n g f : Ideal (TateAlgebra A (Fin n))) :
      Set (TateAlgebra A (Fin n))) := isClosed_closure
  dsimp only [RationalLocalization]
  infer_instance

@[reducible] noncomputable instance (priority := 100) rationalLocalizationAlgebra
    (n : ℕ) (g : A) (f : Fin n → A) :
    Algebra A (RationalLocalization K A n g f) := by
  dsimp only [RationalLocalization]
  infer_instance

@[reducible] noncomputable instance (priority := 100) rationalLocalizationNormedAlgebra
    (n : ℕ) (g : A) (f : Fin n → A) :
    NormedAlgebra K (RationalLocalization K A n g f) := by
  dsimp only [RationalLocalization]
  infer_instance

noncomputable instance (priority := 100) rationalLocalizationCompleteSpace
    (n : ℕ) (g : A) (f : Fin n → A) :
    CompleteSpace (RationalLocalization K A n g f) := by
  dsimp only [RationalLocalization]
  infer_instance

noncomputable instance rationalLocalizationIsUltrametricDist
    (n : ℕ) (g : A) (f : Fin n → A) :
    IsUltrametricDist (RationalLocalization K A n g f) := by
  apply IsUltrametricDist.isUltrametricDist_of_forall_norm_add_le_max_norm
  intro x y
  refine le_of_forall_pos_le_add fun ε hε ↦ ?_
  obtain ⟨a, ha, ha_norm⟩ := Ideal.Quotient.norm_mk_lt x hε
  obtain ⟨b, hb, hb_norm⟩ := Ideal.Quotient.norm_mk_lt y hε
  calc
    ‖x + y‖ = ‖Ideal.Quotient.mk (rationalLocalizationIdeal A n g f) a +
        Ideal.Quotient.mk (rationalLocalizationIdeal A n g f) b‖ := by rw [ha, hb]
    _ = ‖Ideal.Quotient.mk (rationalLocalizationIdeal A n g f) (a + b)‖ := by rw [map_add]
    ‖Ideal.Quotient.mk (rationalLocalizationIdeal A n g f) (a + b)‖ ≤ ‖a + b‖ :=
      Ideal.Quotient.norm_mk_le _ _
    _ ≤ max ‖a‖ ‖b‖ := IsUltrametricDist.norm_add_le_max _ _
    _ ≤ max (‖x‖ + ε) (‖y‖ + ε) :=
      max_le_max ha_norm.le hb_norm.le
    _ = max ‖x‖ ‖y‖ + ε := by rw [max_add_add_right]

noncomputable instance rationalLocalizationIsScalarTower
    (n : ℕ) (g : A) (f : Fin n → A) :
    IsScalarTower K A (RationalLocalization K A n g f) := by
  constructor
  intro x y z
  induction z using Quotient.inductionOn'
  exact congrArg (Ideal.Quotient.mk (rationalLocalizationIdeal A n g f))
    (smul_assoc x y _)

namespace RationalLocalization

private abbrev source (n : ℕ) := TateAlgebra A (Fin n)

/-- The continuous quotient map from the relative Tate algebra. -/
noncomputable def quotientMap (n : ℕ) (g : A) (f : Fin n → A) :
    ContinuousAlgHom K (source (A := A) n) (RationalLocalization K A n g f) where
  __ := Ideal.Quotient.mkₐ K (rationalLocalizationIdeal A n g f)
  cont := continuous_quot_mk

/-- The canonical continuous map from the original algebra to its rational localization. -/
noncomputable def baseMap (n : ℕ) (g : A) (f : Fin n → A) :
    ContinuousAlgHom K A (RationalLocalization K A n g f) where
  __ := (Ideal.Quotient.mkₐ K (rationalLocalizationIdeal A n g f)).comp
    (IsScalarTower.toAlgHom K A (source (A := A) n))
  cont := by
    change Continuous fun a : A ↦
      Ideal.Quotient.mk (rationalLocalizationIdeal A n g f) (TateAlgebra.C A (Fin n) a)
    exact continuous_quot_mk.comp <|
      AddMonoidHomClass.continuous_of_bound (TateAlgebra.C A (Fin n)) 1 fun a ↦ by
        rw [norm_C, one_mul]

@[simp]
theorem baseMap_apply (n : ℕ) (g : A) (f : Fin n → A) (a : A) :
    baseMap K A n g f a = algebraMap A (RationalLocalization K A n g f) a := rfl

/-- The coordinate representing `fᵢ / g`. -/
noncomputable def coordinate (n : ℕ) (g : A) (f : Fin n → A) (i : Fin n) :
    RationalLocalization K A n g f :=
  Ideal.Quotient.mk (rationalLocalizationIdeal A n g f) (tateVariable A (Fin n) i)

@[simp]
theorem quotientMap_C (n : ℕ) (g : A) (f : Fin n → A) (a : A) :
    quotientMap K A n g f (TateAlgebra.C A (Fin n) a) = baseMap K A n g f a := rfl

@[simp]
theorem quotientMap_tateVariable (n : ℕ) (g : A) (f : Fin n → A) (i : Fin n) :
    quotientMap K A n g f (tateVariable A (Fin n) i) = coordinate K A n g f i := rfl

/-- The defining relation `gTᵢ = fᵢ`. -/
@[simp]
theorem baseMap_denominator_mul_coordinate (n : ℕ) (g : A) (f : Fin n → A) (i : Fin n) :
    baseMap K A n g f g * coordinate K A n g f i = baseMap K A n g f (f i) := by
  apply sub_eq_zero.mp
  change Ideal.Quotient.mk (rationalLocalizationIdeal A n g f)
      (TateAlgebra.C A (Fin n) g * tateVariable A (Fin n) i -
        TateAlgebra.C A (Fin n) (f i)) = 0
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  apply subset_closure
  apply Ideal.subset_span
  exact ⟨i, rfl⟩

/-- Every coordinate is power-bounded. -/
theorem isPowerBounded_coordinate (n : ℕ) (g : A) (f : Fin n → A) (i : Fin n) :
    IsPowerBounded (coordinate K A n g f i) := by
  refine ⟨‖(1 : A)‖, ?_⟩
  rintro _ ⟨m, rfl⟩
  change ‖(Ideal.Quotient.mk (rationalLocalizationIdeal A n g f)
    (tateVariable A (Fin n) i)) ^ m‖ ≤ ‖(1 : A)‖
  rw [← map_pow]
  exact (Ideal.Quotient.norm_mk_le _ _).trans (norm_tateVariable_pow_le A (Fin n) i m)

/-- Under the unit-ideal hypothesis, the image of the denominator is a unit. -/
theorem isUnit_baseMap_denominator (n : ℕ) (g : A) (f : Fin n → A)
    (h : IsRationalDatum g f) : IsUnit (baseMap K A n g f g) := by
  let d : RationalLocalization K A n g f := baseMap K A n g f g
  let J : Ideal (RationalLocalization K A n g f) := Ideal.span {d}
  have hgenerators : Set.insert g (Set.range f) ⊆ J.comap (baseMap K A n g f).toRingHom := by
    intro a ha
    change baseMap K A n g f a ∈ J
    rcases ha with rfl | ⟨i, rfl⟩
    · exact Ideal.subset_span (Set.mem_singleton d)
    · rw [← baseMap_denominator_mul_coordinate K A n g f i]
      exact J.mul_mem_right (coordinate K A n g f i) (Ideal.subset_span (Set.mem_singleton d))
  have hle : Ideal.span (Set.insert g (Set.range f)) ≤
      J.comap (baseMap K A n g f).toRingHom := Ideal.span_le.mpr hgenerators
  have hone : (1 : RationalLocalization K A n g f) ∈ J := by
    have htop : (⊤ : Ideal A) ≤ J.comap (baseMap K A n g f).toRingHom := by
      rw [← h]
      exact hle
    simpa using htop (show (1 : A) ∈ (⊤ : Ideal A) by simp)
  apply Ideal.span_singleton_eq_top.mp
  exact (Ideal.eq_top_iff_one J).mpr hone

/-- Map a rational localization by choosing power-bounded coordinate images satisfying the
relations. -/
noncomputable def lift
    {B : Type w} [NormedCommRing B] [NormedAlgebra K B] [CompleteSpace B]
    [IsUltrametricDist B] (n : ℕ) (g : A) (f : Fin n → A)
    (φ : ContinuousAlgHom K A B) (x : Fin n → B)
    (hx : ∀ i, IsPowerBounded (x i)) (hrel : ∀ i, φ g * x i = φ (f i)) :
    ContinuousAlgHom K (RationalLocalization K A n g f) B := by
  let E : ContinuousAlgHom K (source (A := A) n) B :=
    RelativeTateAlgebra.eval K A φ x hx
  have hspan : Ideal.span (Set.range fun i ↦
      TateAlgebra.C A (Fin n) g * tateVariable A (Fin n) i -
        TateAlgebra.C A (Fin n) (f i)) ≤ RingHom.ker E.toRingHom := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, rfl⟩
    change E (TateAlgebra.C A (Fin n) g * tateVariable A (Fin n) i -
      TateAlgebra.C A (Fin n) (f i)) = 0
    rw [map_sub, map_mul, RelativeTateAlgebra.eval_C,
      RelativeTateAlgebra.eval_tateVariable, RelativeTateAlgebra.eval_C, hrel i, sub_self]
  have hclosed : IsClosed ((RingHom.ker E.toRingHom : Ideal (source (A := A) n)) :
      Set (source (A := A) n)) := by
    change IsClosed {z : source (A := A) n | E z = 0}
    exact isClosed_singleton.preimage E.continuous
  have hI : rationalLocalizationIdeal A n g f ≤ RingHom.ker E.toRingHom :=
    closure_minimal hspan hclosed
  let L : (RationalLocalization K A n g f) →ₐ[K] B :=
    Ideal.Quotient.liftₐ (rationalLocalizationIdeal A n g f) E.toAlgHom
      (fun a ha ↦ RingHom.mem_ker.mp (hI ha))
  exact
    { L with
      cont := by
        apply (QuotientRing.isOpenQuotientMap_mk
          (rationalLocalizationIdeal A n g f)).isQuotientMap.continuous_iff.mpr
        change Continuous fun s : source A n ↦
          L (Ideal.Quotient.mk (rationalLocalizationIdeal A n g f) s)
        convert E.continuous using 1
        funext s
        exact Ideal.Quotient.lift_mk _ _ _ }

@[simp]
theorem lift_comp_baseMap
    {B : Type w} [NormedCommRing B] [NormedAlgebra K B] [CompleteSpace B]
    [IsUltrametricDist B] (n : ℕ) (g : A) (f : Fin n → A)
    (φ : ContinuousAlgHom K A B) (x : Fin n → B)
    (hx : ∀ i, IsPowerBounded (x i)) (hrel : ∀ i, φ g * x i = φ (f i)) :
    (lift K A n g f φ x hx hrel).comp (baseMap K A n g f) = φ := by
  apply ContinuousAlgHom.ext
  intro a
  change RelativeTateAlgebra.eval K A φ x hx (TateAlgebra.C A (Fin n) a) = φ a
  exact RelativeTateAlgebra.eval_C K A φ x hx a

@[simp]
theorem lift_coordinate
    {B : Type w} [NormedCommRing B] [NormedAlgebra K B] [CompleteSpace B]
    [IsUltrametricDist B] (n : ℕ) (g : A) (f : Fin n → A)
    (φ : ContinuousAlgHom K A B) (x : Fin n → B)
    (hx : ∀ i, IsPowerBounded (x i)) (hrel : ∀ i, φ g * x i = φ (f i)) (i : Fin n) :
    lift K A n g f φ x hx hrel (coordinate K A n g f i) = x i := by
  change RelativeTateAlgebra.eval K A φ x hx (tateVariable A (Fin n) i) = x i
  exact RelativeTateAlgebra.eval_tateVariable K A φ x hx i

/-- Continuous homomorphisms agree if they agree on the base and all coordinates. -/
@[ext]
theorem hom_ext
    {B : Type w} [NormedCommRing B] [NormedAlgebra K B]
    (n : ℕ) (g : A) (f : Fin n → A)
    (φ ψ : ContinuousAlgHom K (RationalLocalization K A n g f) B)
    (hbase : φ.comp (baseMap K A n g f) = ψ.comp (baseMap K A n g f))
    (hcoordinate : ∀ i, φ (coordinate K A n g f i) = ψ (coordinate K A n g f i)) :
    φ = ψ := by
  have hsource : φ.comp (quotientMap K A n g f) = ψ.comp (quotientMap K A n g f) := by
    apply RelativeTateAlgebra.hom_ext K A
    · intro a
      exact congrArg (fun q : ContinuousAlgHom K A B ↦ q a) hbase
    · exact hcoordinate
  apply ContinuousAlgHom.ext
  intro z
  obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective z
  exact congrArg (fun q : ContinuousAlgHom K (source A n) B ↦ q s) hsource

end RationalLocalization

/-- A rational localization is affinoid when its coefficient algebra has a continuous surjective
finite Tate-algebra presentation. -/
theorem isAffinoidAlgebra_rationalLocalization_of_surjective (m : ℕ)
    (π : ContinuousAlgHom K (TateAlgebra K (Fin m)) A) (hπ : Function.Surjective π)
    (n : ℕ) (g : A) (f : Fin n → A) :
    IsAffinoidAlgebra K (RationalLocalization K A n g f) :=
  IsAffinoidAlgebra.quotient K
    (isAffinoidAlgebra_relativeTateAlgebra_of_surjective K A m π hπ n)
    (rationalLocalizationIdeal A n g f)

end Rigid
