import Mathlib.Analysis.Normed.Unbundled.SpectralNorm
import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import Mathlib.RingTheory.Ideal.MinimalPrime.Noetherian
import Mathlib.RingTheory.Polynomial.Subring
import Rigid.AffinoidAlgebra.FiniteModuleBounded
import Rigid.AffinoidAlgebra.NoetherNormalization
import Rigid.AffinoidAlgebra.SpectralRadius
import Rigid.Berkovich.CompletedResidue
import Rigid.TateAlgebra.Complete
import Rigid.TateAlgebra.Domain
import Rigid.TateAlgebra.UniqueFactorization

set_option linter.style.header false
set_option linter.unusedSectionVars false

/-!
# Spectral polynomial relations

This file isolates the algebraic part of Proposition 4.5.3 of the cited draft.  A monic
polynomial relation whose coefficients belong to a fixed subring is stable under products and
powers.  Consequently, relations obtained after quotienting by every minimal prime of a
Noetherian ring combine to a relation in the original ring: their product vanishes modulo every
minimal prime, hence is nilpotent, and a power of that product vanishes.

For a Tate-algebra base, a relation with coefficients in the Gauss unit ball is exactly the
integrality certificate needed in the power-boundedness argument.  Thus the remaining analytic
content of Proposition 4.5.3 is cleanly reduced to the domain case.
-/

open Filter
open scoped BigOperators Polynomial Topology

universe u v

namespace Rigid

namespace SpectralPolynomial

variable {R : Type u} {B : Type v}

section MinimalPolynomial

variable [CommRing R] [CommRing B] [IsDomain R] [IsIntegrallyClosed R] [IsDomain B]
variable [Algebra R B] [Module.IsTorsionFree R B]

/-- Lemma 4.5.5, in the slightly more general integrally-closed form already supported by
Mathlib: an integral element in a domain has a unique monic annihilating polynomial of minimal
degree. -/
theorem existsUnique_monic_minimalPolynomial (b : B) (hb : IsIntegral R b) :
    ∃! P : R[X], P.Monic ∧ Polynomial.aeval b P = 0 ∧
      ∀ Q : R[X], Q.Monic → Polynomial.aeval b Q = 0 → P.degree ≤ Q.degree := by
  refine ⟨minpoly R b, ⟨minpoly.monic hb, minpoly.aeval R b, ?_⟩, ?_⟩
  · intro Q hQmonic hQeval
    exact minpoly.min R b hQmonic hQeval
  · intro P hP
    exact IsIntegrallyClosed.minpoly.unique hP.1 hP.2.1 hP.2.2

/-- The quotient by the minimal polynomial is the subalgebra generated by the element, the
second assertion of Lemma 4.5.5.  `AdjoinRoot P` is `R[X] / (P)`. -/
noncomputable def minimalPolynomialQuotientEquivAdjoin (b : B) (hb : IsIntegral R b) :
    AdjoinRoot (minpoly R b) ≃ₐ[R] Algebra.adjoin R ({b} : Set B) :=
  minpoly.equivAdjoin hb

end MinimalPolynomial

/-- Every coefficient of `P` belongs to the subring `S`. -/
def CoefficientsIn [Ring R] (S : Subring R) (P : R[X]) : Prop :=
  ∀ i : ℕ, P.coeff i ∈ S

namespace CoefficientsIn

variable [CommRing R] {S : Subring R} {P Q : R[X]}

theorem one : CoefficientsIn S (1 : R[X]) := by
  intro i
  simp only [Polynomial.coeff_one]
  split_ifs <;> simp

theorem mul (hP : CoefficientsIn S P) (hQ : CoefficientsIn S Q) :
    CoefficientsIn S (P * Q) := by
  intro n
  rw [Polynomial.coeff_mul]
  exact Subring.sum_mem S fun i _ ↦ S.mul_mem (hP i.1) (hQ i.2)

theorem pow (hP : CoefficientsIn S P) (n : ℕ) : CoefficientsIn S (P ^ n) := by
  induction n with
  | zero => simpa using (one (S := S))
  | succ n ih => simpa [pow_succ] using ih.mul hP

theorem prod {ι : Type*} {s : Finset ι} {P : ι → R[X]}
    (hP : ∀ i ∈ s, CoefficientsIn S (P i)) :
    CoefficientsIn S (∏ i ∈ s, P i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using (one (S := S))
  | @insert a s ha ih =>
      simp only [Finset.prod_insert, ha, not_false_eq_true]
      exact (hP a (Finset.mem_insert_self a s)).mul
        (ih fun i hi ↦ hP i (Finset.mem_insert_of_mem hi))

end CoefficientsIn

/-- A monic polynomial over `R`, with coefficients in `S`, that annihilates `b` through `f`. -/
def HasMonicRelation [CommRing R] [CommRing B] (S : Subring R) (f : R →+* B)
    (b : B) : Prop :=
  ∃ P : R[X], P.Monic ∧ CoefficientsIn S P ∧ Polynomial.eval₂ f b P = 0

/-- A monic relation with coefficients in `S` makes the element integral over the image of `S`. -/
theorem isIntegral_image_of_hasMonicRelation [CommRing R] [CommRing B]
    (S : Subring R) (f : R →+* B) (b : B) (h : HasMonicRelation S f b) :
    IsIntegral (S.map f) b := by
  classical
  obtain ⟨P, hPmonic, hPcoeff, hPeval⟩ := h
  let T : Subring B := S.map f
  have hcoeffs : ((P.map f).coeffs : Set B) ⊆ T := by
    intro c hc
    have hc' : c ∈ (P.map f).coeffs := hc
    obtain ⟨i, hi, rfl⟩ := Polynomial.mem_coeffs_iff.mp hc'
    rw [Polynomial.coeff_map]
    exact ⟨P.coeff i, hPcoeff i, rfl⟩
  let Q : T[X] := (P.map f).toSubring T hcoeffs
  refine ⟨Q, ?_, ?_⟩
  · exact (Polynomial.monic_toSubring (P.map f) T hcoeffs).mpr (hPmonic.map f)
  · change Polynomial.eval₂ (Subring.subtype T) b Q = 0
    rw [← Polynomial.eval_map, Polynomial.map_toSubring]
    simpa only [Polynomial.eval_map] using hPeval

/-- The algebraic reduction in Proposition 4.5.3 from a Noetherian ring to its domain
quotients.  Relations modulo the minimal primes are multiplied; the resulting value lies in the
nilradical, so a positive power of the product is an actual relation. -/
theorem hasMonicRelation_of_minimalPrime_quotients [CommRing R] [CommRing B]
    [Nontrivial B] [IsNoetherianRing B] (S : Subring R) (f : R →+* B) (b : B)
    (h : ∀ q ∈ minimalPrimes B,
      HasMonicRelation S ((Ideal.Quotient.mk q).comp f) (Ideal.Quotient.mk q b)) :
    HasMonicRelation S f b := by
  classical
  let MinPrime := {q : Ideal B // q ∈ minimalPrimes B}
  letI : Fintype MinPrime :=
    (minimalPrimes.finite_of_isNoetherianRing B).fintype
  let P : MinPrime → R[X] := fun q ↦ Classical.choose (h q.1 q.2)
  have hP (q : MinPrime) :
      (P q).Monic ∧ CoefficientsIn S (P q) ∧
        Polynomial.eval₂ ((Ideal.Quotient.mk q.1).comp f)
          (Ideal.Quotient.mk q.1 b) (P q) = 0 :=
    Classical.choose_spec (h q.1 q.2)
  let Q : R[X] := ∏ q : MinPrime, P q
  have hQmonic : Q.Monic := by
    dsimp only [Q]
    exact Polynomial.monic_prod_of_monic Finset.univ P fun q _ ↦ (hP q).1
  have hQcoeff : CoefficientsIn S Q := by
    dsimp only [Q]
    exact CoefficientsIn.prod fun q _ ↦ (hP q).2.1
  have hQeval_mem (q : Ideal B) (hq : q ∈ minimalPrimes B) :
      Polynomial.eval₂ f b Q ∈ q := by
    rw [← Ideal.Quotient.eq_zero_iff_mem]
    rw [Polynomial.hom_eval₂]
    dsimp only [Q]
    rw [Polynomial.eval₂_finsetProd]
    exact Finset.prod_eq_zero (Finset.mem_univ (⟨q, hq⟩ : MinPrime))
      (hP (⟨q, hq⟩ : MinPrime)).2.2
  have hQeval_sInf : Polynomial.eval₂ f b Q ∈ sInf (minimalPrimes B) := by
    rw [Ideal.mem_sInf]
    exact hQeval_mem
  have hQeval_radical : Polynomial.eval₂ f b Q ∈ (⊥ : Ideal B).radical := by
    simpa only [Ideal.sInf_minimalPrimes] using hQeval_sInf
  have hnil : IsNilpotent (Polynomial.eval₂ f b Q) :=
    (mem_nilradical (R := B)).mp hQeval_radical
  obtain ⟨e, he⟩ := hnil
  refine ⟨Q ^ e, hQmonic.pow e, hQcoeff.pow e, ?_⟩
  rw [Polynomial.eval₂_pow]
  exact he

section Normed

variable [NormedRing R] [NormOneClass R] [Nontrivial R]

/-- The coefficient bound direction of `Polynomial.spectralValue_le_one_iff` needs no division
in the coefficient ring. -/
theorem norm_coeff_le_one_of_spectralValue_le_one {P : R[X]} (hP : P.Monic)
    (hsp : spectralValue P ≤ 1) (n : ℕ) : ‖P.coeff n‖ ≤ 1 := by
  obtain hn | hn | hn := lt_trichotomy P.natDegree n
  · simp [Polynomial.coeff_eq_zero_of_natDegree_lt hn]
  · rw [← hn, hP.coeff_natDegree, norm_one]
  · have hterm : spectralValueTerms P n ≤ 1 :=
      (le_ciSup (spectralValueTerms_bddAbove P) n).trans hsp
    contrapose! hterm
    rw [spectralValueTerms_of_lt_natDegree P hn]
    exact Real.one_lt_rpow hterm (by simp [hn])

variable {D : Type v} [NormedRing D] [Nontrivial D]

/-- Spectral value does not increase when the coefficients are mapped by a norm-nonincreasing
ring homomorphism. -/
theorem spectralValue_map_le (f : R →+* D) (hf : ∀ r, ‖f r‖ ≤ ‖r‖)
    {P : R[X]} (hP : P.Monic) : spectralValue (P.map f) ≤ spectralValue P := by
  rw [spectralValue]
  apply ciSup_le
  intro n
  calc
    spectralValueTerms (P.map f) n ≤ spectralValueTerms P n := by
      have hdeg : (P.map f).natDegree = P.natDegree := hP.natDegree_map f
      simp only [spectralValueTerms, hdeg, Polynomial.coeff_map]
      split_ifs with hn
      · have hexp : 0 ≤ 1 / (P.natDegree - n : ℝ) := by
          rw [one_div_nonneg, sub_nonneg, Nat.cast_le]
          exact hn.le
        exact Real.rpow_le_rpow (norm_nonneg _) (hf (P.coeff n)) hexp
      · exact le_rfl
    _ ≤ ⨆ n, spectralValueTerms P n :=
      le_ciSup (spectralValueTerms_bddAbove P) n

/-- An isometric coefficient map preserves spectral value. -/
theorem spectralValue_map_eq (f : R →+* D) (hf : ∀ r, ‖f r‖ = ‖r‖)
    {P : R[X]} (hP : P.Monic) : spectralValue (P.map f) = spectralValue P := by
  apply iSup_congr
  intro n
  have hdeg : (P.map f).natDegree = P.natDegree := hP.natDegree_map f
  simp only [spectralValueTerms, hdeg, Polynomial.coeff_map, hf]

end Normed

section BoundedPowerRealization

variable {E : Type u} [NormedCommRing E]
variable {L : Type v} [NormedDivisionRing L]

/-- A bounded function that realizes all powers of `c` as powers of `z` bounds the norm of `z`
by the spectral radius of `c`.  No additivity or multiplicativity of the function away from those
powers is needed.  This is the asymptotic estimate used after extending the root evaluation to a
linear functional on a finite algebra. -/
theorem norm_le_spectralRadius_of_bounded_power_realization [Nontrivial E]
    (c : E) (z : L) (F : E → L) (M : ℝ) (hM : 0 < M)
    (hFpow : ∀ m : ℕ, F (c ^ m) = z ^ m)
    (hF : ∀ a : E, ‖F a‖ ≤ M * ‖a‖) :
    ‖z‖ ≤ BerkovichSpectrum.spectralRadius E c := by
  let μ : RingSeminorm E := BerkovichSpectrum.normalizedNormSeminorm E
  let D : ℝ := M * ‖(1 : E)‖
  have hD : 0 < D := mul_pos hM (norm_pos_iff.mpr one_ne_zero)
  have hrootD : Tendsto (fun n : ℕ ↦ D ^ (1 / (n : ℝ))) atTop (𝓝 1) := by
    convert tendsto_const_nhds.rpow tendsto_one_div_atTop_nhds_zero_nat
      (Or.inl hD.ne') using 1
    rw [Real.rpow_zero]
  have hlim : Tendsto (fun n : ℕ ↦
      smoothingSeminormSeq μ c n * D ^ (1 / (n : ℝ))) atTop
      (𝓝 (BerkovichSpectrum.spectralRadius E c)) := by
    simpa only [μ, mul_one] using (BerkovichSpectrum.tendsto_spectralRadius E c).mul hrootD
  apply ge_of_tendsto hlim
  filter_upwards [eventually_ge_atTop 1] with m hm
  have hm0 : (m : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.one_le_iff_ne_zero.mp hm)
  have hexp : 0 < 1 / (m : ℝ) := one_div_pos.mpr (Nat.cast_pos.mpr (by omega))
  calc
    ‖z‖ = (‖z‖ ^ m) ^ (1 / (m : ℝ)) := by
      rw [← Real.rpow_natCast, ← Real.rpow_mul (norm_nonneg z),
        mul_one_div_cancel hm0, Real.rpow_one]
    _ = ‖z ^ m‖ ^ (1 / (m : ℝ)) := by rw [norm_pow]
    _ = ‖F (c ^ m)‖ ^ (1 / (m : ℝ)) := by rw [hFpow]
    _ ≤ (M * ‖c ^ m‖) ^ (1 / (m : ℝ)) :=
      Real.rpow_le_rpow (norm_nonneg _) (hF _) hexp.le
    _ ≤ (D * μ (c ^ m)) ^ (1 / (m : ℝ)) := by
      apply Real.rpow_le_rpow (mul_nonneg hM.le (norm_nonneg _)) _ hexp.le
      calc
        M * ‖c ^ m‖ ≤ M * (‖(1 : E)‖ * μ (c ^ m)) :=
          mul_le_mul_of_nonneg_left
            (BerkovichSpectrum.norm_le_norm_one_mul_normalizedNormSeminorm E (c ^ m)) hM.le
        _ = D * μ (c ^ m) := by simp only [D, mul_assoc]
    _ = smoothingSeminormSeq μ c m * D ^ (1 / (m : ℝ)) := by
      rw [Real.mul_rpow hD.le (apply_nonneg μ _), mul_comm]

end BoundedPowerRealization

section FiniteModulePowerRealization

variable {k : Type u} [NontriviallyNormedField k]
variable {R : Type v} [NormedCommRing R] [NormedAlgebra k R] [CompleteSpace R]
variable {E : Type w} [NormedCommRing E] [NormedAlgebra k E] [CompleteSpace E] [Nontrivial E]
variable {L : Type*} [NormedDivisionRing L] [NormedSpace k L]
variable [Module R E] [Module R L] [IsScalarTower k R E] [IsScalarTower k R L]
variable [ContinuousSMul R E] [ContinuousSMul R L] [Module.Finite R E]

include k in
/-- Once the root evaluation has been extended to an `R`-linear map on the finite algebra, its
boundedness and the lower spectral-radius inequality are automatic. -/
theorem norm_le_spectralRadius_of_finiteModule_power_realization
    (c : E) (z : L) (F : E →ₗ[R] L) (hFpow : ∀ m : ℕ, F (c ^ m) = z ^ m) :
    ‖z‖ ≤ BerkovichSpectrum.spectralRadius E c := by
  obtain ⟨M, hM, hF⟩ :=
    Rigid.LinearMap.exists_bound_of_module_finite (K := k) F
  exact norm_le_spectralRadius_of_bounded_power_realization c z F M hM hFpow hF

end FiniteModulePowerRealization

section Tate

variable (K : Type u) [NontriviallyNormedField K] [IsUltrametricDist K]

section Algebraic

variable {C : Type v} [CommRing C]

/-- A polynomial relation over a Tate algebra whose coefficients lie in its Gauss unit ball. -/
def HasUnitBallRelation (n : ℕ) (f : TateAlgebra K (Fin n) →+* C) (c : C) : Prop :=
  HasMonicRelation (TateAlgebra.unitBallSubring K n) f c

/-- A unit-ball polynomial relation is the corresponding integrality certificate. -/
theorem isIntegral_image_unitBall_of_hasUnitBallRelation (n : ℕ)
    (f : TateAlgebra K (Fin n) →+* C) (c : C) (h : HasUnitBallRelation K n f c) :
    IsIntegral ((TateAlgebra.unitBallSubring K n).map f) c :=
  isIntegral_image_of_hasMonicRelation _ _ _ h

/-- The minimal-prime reduction of Proposition 4.5.3 in its unit-ball form.  It is enough to
construct a unit-ball relation after quotienting by every minimal prime; multiplying those
relations and taking a power removes the nilpotent error. -/
theorem hasUnitBallRelation_of_minimalPrime_quotients [Nontrivial C] [IsNoetherianRing C]
    (n : ℕ) (f : TateAlgebra K (Fin n) →+* C) (c : C)
    (h : ∀ q ∈ minimalPrimes C,
      HasUnitBallRelation K n ((Ideal.Quotient.mk q).comp f) (Ideal.Quotient.mk q c)) :
    HasUnitBallRelation K n f c :=
  hasMonicRelation_of_minimalPrime_quotients _ _ _ h

end Algebraic

variable [CompleteSpace K]
variable {C : Type v}
variable [NormedCommRing C] [NormedAlgebra K C] [CompleteSpace C] [IsUltrametricDist C]

/-- Componentwise unit-ball relations over one continuous Tate-algebra map combine into the
integral certificate used by Proposition 4.5.12. -/
theorem hasUnitBallIntegralCertificate_of_minimalPrime_quotients
    [Nontrivial C] [IsNoetherianRing C] {n : ℕ}
    (π : ContinuousAlgHom K (TateAlgebra K (Fin n)) C) (c : C)
    (h : ∀ q ∈ minimalPrimes C,
      HasUnitBallRelation K n ((Ideal.Quotient.mk q).comp π.toRingHom)
        (Ideal.Quotient.mk q c)) :
    HasUnitBallIntegralCertificate K c :=
  ⟨n, π, isIntegral_image_unitBall_of_hasUnitBallRelation K n π.toRingHom c
    (hasUnitBallRelation_of_minimalPrime_quotients K n π.toRingHom c h)⟩

/-- The completed residue field of the Gauss point of a finite Tate algebra. -/
abbrev GaussResidueField (n : ℕ) :=
  BerkovichSpectrumOver.CompletedResidueField (TateAlgebra.gaussPoint K n)

/-- An algebraic closure of the completed Gauss residue field. -/
abbrev GaussAlgebraicClosure (n : ℕ) := AlgebraicClosure (GaussResidueField K n)

/-- Evaluation of Tate-algebra coefficients in an algebraic closure of the completed Gauss
residue field. -/
noncomputable def gaussAlgebraicClosureMap (n : ℕ) :
    TateAlgebra K (Fin n) →+* GaussAlgebraicClosure K n :=
  (algebraMap (GaussResidueField K n) (GaussAlgebraicClosure K n)).comp
    (BerkovichSpectrumOver.completedResidueMap (TateAlgebra.gaussPoint K n))

@[simp]
theorem spectralNorm_gaussAlgebraicClosureMap (n : ℕ) (a : TateAlgebra K (Fin n)) :
    spectralNorm (GaussResidueField K n) (GaussAlgebraicClosure K n)
      (gaussAlgebraicClosureMap K n a) = ‖a‖ := by
  rw [gaussAlgebraicClosureMap, RingHom.comp_apply, spectralNorm_extends,
    BerkovichSpectrumOver.norm_completedResidueMap, TateAlgebra.gaussPoint_apply]

/-- Evaluation in the completed Gauss residue field, and hence in its algebraic closure, is
injective. -/
theorem gaussAlgebraicClosureMap_injective (n : ℕ) :
    Function.Injective (gaussAlgebraicClosureMap K n) := by
  rw [injective_iff_map_eq_zero]
  intro a ha
  apply norm_eq_zero.mp
  rw [← spectralNorm_gaussAlgebraicClosureMap K n a, ha, spectralNorm_zero]

/-- A monic polynomial annihilating an element of a nontrivial algebra has positive degree. -/
theorem natDegree_pos_of_monic_relation [Nontrivial C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →+* C) (c : C)
    {P : (TateAlgebra K (Fin n))[X]} (hP : P.Monic)
    (hPeval : Polynomial.eval₂ π c P = 0) : 0 < P.natDegree := by
  have hroot : Polynomial.aeval c (P.map π) = 0 := by
    simpa only [Polynomial.aeval_def, Polynomial.eval₂_map, Algebra.algebraMap_self,
      RingHom.id_comp] using hPeval
  have hdeg := Polynomial.natDegree_pos_of_monic_of_aeval_eq_zero (hP.map π) hroot
  rwa [hP.natDegree_map] at hdeg

/-- The root-theoretic part of Lemma 4.5.11 and Proposition 4.5.7.  A positive-degree monic
polynomial over a Tate algebra has a root over the completed Gauss residue field whose extended
norm is exactly its spectral value.  This is the existing nonarchimedean norm-extension theorem
from Mathlib, together with the isometry of evaluation at the Gauss point. -/
theorem exists_gaussRoot_spectralNorm_eq_spectralValue {n : ℕ}
    {P : (TateAlgebra K (Fin n))[X]} (hP : P.Monic) (hPdeg : 0 < P.natDegree) :
    ∃ z : GaussAlgebraicClosure K n,
      Polynomial.aeval z (P.map (gaussAlgebraicClosureMap K n)) = 0 ∧
        spectralNorm (GaussResidueField K n) (GaussAlgebraicClosure K n) z = spectralValue P := by
  classical
  let H := GaussResidueField K n
  let L := GaussAlgebraicClosure K n
  let ψ : TateAlgebra K (Fin n) →+* H :=
    BerkovichSpectrumOver.completedResidueMap (TateAlgebra.gaussPoint K n)
  let P_H : H[X] := P.map ψ
  have hP_H : P_H.Monic := hP.map ψ
  have hsplit : (P_H.map (algebraMap H L)).Splits := IsAlgClosed.splits _
  obtain ⟨s, hs⟩ := Polynomial.splits_iff_exists_multiset.mp hsplit
  have hlc : algebraMap H L P_H.leadingCoeff = 1 := by
    rw [hP_H.leadingCoeff, map_one]
  rw [Polynomial.leadingCoeff_map, hlc, Polynomial.C_1, one_mul] at hs
  have hcard : s.card = P.natDegree := by
    rw [← Polynomial.natDegree_multiset_prod_X_sub_C_eq_card, ← hs,
      hP_H.natDegree_map, hP.natDegree_map]
  have hsne : s ≠ 0 := by
    intro hs0
    rw [hs0, Multiset.card_zero] at hcard
    omega
  letI : NormedField L := spectralNorm.normedField H L
  letI : NormedAlgebra H L := spectralNorm.normedAlgebra H L
  letI : IsUltrametricDist L :=
    IsUltrametricDist.isUltrametricDist_of_isNonarchimedean_norm fun a b ↦
      isNonarchimedean_spectralNorm a b
  obtain ⟨z, hzs, hzmax⟩ := Multiset.exists_max_image norm hsne
  refine ⟨z, ?_, ?_⟩
  · have hzroot : Polynomial.aeval z P_H = 0 :=
      Polynomial.aeval_root_of_mapAlg_eq_multiset_prod_X_sub_C (R := H) s hzs (by
        simpa only [Polynomial.mapAlg_eq_map] using hs)
    simpa only [Polynomial.aeval_def, P_H, ψ, gaussAlgebraicClosureMap,
      Polynomial.eval₂_map, RingHom.comp_assoc, Algebra.algebraMap_self,
      RingHom.id_comp] using hzroot
  · have hmax : (⨆ x : L, if x ∈ s then ‖x‖ else 0) = ‖z‖ := by
      have hbdd : BddAbove (Set.range fun x : L ↦ if x ∈ s then ‖x‖ else 0) := by
        refine ⟨‖z‖, ?_⟩
        rintro _ ⟨x, rfl⟩
        change (if x ∈ s then ‖x‖ else 0) ≤ ‖z‖
        split_ifs with hx
        · exact hzmax x hx
        · exact norm_nonneg z
      apply le_antisymm
      · apply ciSup_le
        intro x
        change (if x ∈ s then ‖x‖ else 0) ≤ ‖z‖
        split_ifs with hx
        · exact hzmax x hx
        · exact norm_nonneg z
      · simpa only [if_pos hzs] using (le_ciSup hbdd z)
    let ν : AlgebraNorm H L := (NormedAlgebra.toMulAlgebraNorm H L).toAlgebraNorm
    have hνpow : IsPowMul ν := by
      intro a m _
      change ‖a ^ m‖ = ‖a‖ ^ m
      exact norm_pow a m
    have hνna : IsNonarchimedean ν := by
      intro a b
      change ‖a + b‖ ≤ max ‖a‖ ‖b‖
      exact IsUltrametricDist.norm_add_le_max a b
    have hνone : ν 1 = 1 := by
      change ‖(1 : L)‖ = 1
      exact norm_one
    have hspectral : (⨆ x : L, if x ∈ s then ‖x‖ else 0) = spectralValue P_H := by
      simpa only [ν, MulAlgebraNorm.coe_AlgebraNorm,
        NormedAlgebra.toMulAlgebraNorm_apply] using
        (max_norm_root_eq_spectralValue hνpow hνna hνone P_H s hs)
    have hψ (a : TateAlgebra K (Fin n)) : ‖ψ a‖ = ‖a‖ := by
      change ‖BerkovichSpectrumOver.completedResidueMap (TateAlgebra.gaussPoint K n) a‖ = ‖a‖
      rw [BerkovichSpectrumOver.norm_completedResidueMap,
        TateAlgebra.gaussPoint_apply]
    calc
      spectralNorm H L z = ‖z‖ := rfl
      _ = ⨆ x : L, if x ∈ s then ‖x‖ else 0 := hmax.symm
      _ = spectralValue P_H := hspectral
      _ = spectralValue P := spectralValue_map_eq ψ hψ hP

/-- A chosen root of maximal norm over the completed Gauss residue field. -/
noncomputable def gaussMaxRoot {n : ℕ} {P : (TateAlgebra K (Fin n))[X]}
    (hP : P.Monic) (hPdeg : 0 < P.natDegree) : GaussAlgebraicClosure K n :=
  Classical.choose (exists_gaussRoot_spectralNorm_eq_spectralValue K hP hPdeg)

@[simp]
theorem aeval_gaussMaxRoot {n : ℕ} {P : (TateAlgebra K (Fin n))[X]}
    (hP : P.Monic) (hPdeg : 0 < P.natDegree) :
    Polynomial.aeval (gaussMaxRoot K hP hPdeg)
      (P.map (gaussAlgebraicClosureMap K n)) = 0 :=
  (Classical.choose_spec (exists_gaussRoot_spectralNorm_eq_spectralValue K hP hPdeg)).1

@[simp]
theorem eval₂_gaussMaxRoot {n : ℕ} {P : (TateAlgebra K (Fin n))[X]}
    (hP : P.Monic) (hPdeg : 0 < P.natDegree) :
    Polynomial.eval₂ (gaussAlgebraicClosureMap K n) (gaussMaxRoot K hP hPdeg) P = 0 := by
  simpa only [Polynomial.aeval_def, Polynomial.eval₂_map, Algebra.algebraMap_self,
    RingHom.id_comp] using aeval_gaussMaxRoot K hP hPdeg

@[simp]
theorem spectralNorm_gaussMaxRoot {n : ℕ} {P : (TateAlgebra K (Fin n))[X]}
    (hP : P.Monic) (hPdeg : 0 < P.natDegree) :
    spectralNorm (GaussResidueField K n) (GaussAlgebraicClosure K n)
      (gaussMaxRoot K hP hPdeg) = spectralValue P :=
  (Classical.choose_spec (exists_gaussRoot_spectralNorm_eq_spectralValue K hP hPdeg)).2

/-- Evaluation at a Gauss-fiber root, as a homomorphism out of the polynomial quotient. -/
noncomputable def gaussRootLift {n : ℕ} (P : (TateAlgebra K (Fin n))[X])
    (z : GaussAlgebraicClosure K n)
    (hz : Polynomial.aeval z (P.map (gaussAlgebraicClosureMap K n)) = 0) :
    AdjoinRoot P →+* GaussAlgebraicClosure K n :=
  AdjoinRoot.lift (gaussAlgebraicClosureMap K n) z (by
    simpa only [Polynomial.aeval_def, Polynomial.eval₂_map, Algebra.algebraMap_self,
      RingHom.id_comp] using hz)

@[simp]
theorem gaussRootLift_root {n : ℕ} (P : (TateAlgebra K (Fin n))[X])
    (z : GaussAlgebraicClosure K n)
    (hz : Polynomial.aeval z (P.map (gaussAlgebraicClosureMap K n)) = 0) :
    gaussRootLift K P z hz (AdjoinRoot.root P) = z :=
  AdjoinRoot.lift_root _

/-- The precise finite-module functional needed after the Gauss root has been constructed.  The
function need only be bounded and carry the powers of `c` to the powers of the chosen root; in the
domain proof it is obtained by extending root evaluation linearly over the fraction field. -/
def HasBoundedGaussRootRealization (n : ℕ) (c : C)
    (P : (TateAlgebra K (Fin n))[X]) : Prop :=
  ∃ z : GaussAlgebraicClosure K n,
    Polynomial.aeval z (P.map (gaussAlgebraicClosureMap K n)) = 0 ∧
    spectralNorm (GaussResidueField K n) (GaussAlgebraicClosure K n) z = spectralValue P ∧
    ∃ (F : C → GaussAlgebraicClosure K n) (M : ℝ), 0 < M ∧
      (∀ m : ℕ, F (c ^ m) = z ^ m) ∧
      ∀ a : C,
        spectralNorm (GaussResidueField K n) (GaussAlgebraicClosure K n) (F a) ≤ M * ‖a‖

/-- The sole remaining functional in the domain argument, stated for the canonical maximal Gauss
root.  Lemma 4.5.5 identifies the algebra generated by `c` with the polynomial quotient; one then
extends its root-evaluation map linearly across the finite fraction-field extension and uses the
Banach open mapping theorem for this bound. -/
def HasBoundedGaussMaxRootFunctional {n : ℕ} (c : C)
    {P : (TateAlgebra K (Fin n))[X]} (hP : P.Monic) (hPdeg : 0 < P.natDegree) : Prop :=
  ∃ (F : C → GaussAlgebraicClosure K n) (M : ℝ), 0 < M ∧
    (∀ m : ℕ, F (c ^ m) = gaussMaxRoot K hP hPdeg ^ m) ∧
    ∀ a : C,
      spectralNorm (GaussResidueField K n) (GaussAlgebraicClosure K n) (F a) ≤ M * ‖a‖

/-- The remaining algebraic identity in the domain proof of Proposition 4.5.7: after passing to
fraction fields, the maximal Gauss root is a root of the minimal polynomial of `c`. -/
def HasFractionMinpolyGaussRoot [IsDomain C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπinj : Function.Injective π) (c : C)
    {P : (TateAlgebra K (Fin n))[X]} (hP : P.Monic) (hPdeg : 0 < P.natDegree) : Prop :=
  let A := TateAlgebra K (Fin n)
  let L := GaussAlgebraicClosure K n
  letI : Algebra A C := π.toRingHom.toAlgebra
  letI : FaithfulSMul A C :=
    (faithfulSMul_iff_algebraMap_injective A C).mpr hπinj
  letI : Algebra A L := (gaussAlgebraicClosureMap K n).toAlgebra
  letI : FaithfulSMul A L :=
    (faithfulSMul_iff_algebraMap_injective A L).mpr
      (gaussAlgebraicClosureMap_injective K n)
  letI : Algebra (FractionRing A) (FractionRing C) :=
    FractionRing.liftAlgebra A (FractionRing C)
  Polynomial.eval₂ (IsFractionRing.lift (gaussAlgebraicClosureMap_injective K n))
    (gaussMaxRoot K hP hPdeg)
    (minpoly (FractionRing A) (algebraMap C (FractionRing C) c)) = 0

/-- A Tate-algebra relation becomes the minimal polynomial of the element after passing to the
fraction fields.  This is the algebraic conclusion of Lemma 4.5.5 used in Proposition 4.5.7. -/
def IsFractionMinpoly [IsDomain C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπinj : Function.Injective π) (c : C)
    (P : (TateAlgebra K (Fin n))[X]) : Prop :=
  let A := TateAlgebra K (Fin n)
  letI : Algebra A C := π.toRingHom.toAlgebra
  letI : FaithfulSMul A C :=
    (faithfulSMul_iff_algebraMap_injective A C).mpr hπinj
  letI : Algebra (FractionRing A) (FractionRing C) :=
    FractionRing.liftAlgebra A (FractionRing C)
  P.map (algebraMap A (FractionRing A)) =
    minpoly (FractionRing A) (algebraMap C (FractionRing C) c)

/-- The minimal polynomial over the Tate algebra, using the algebra structure induced by `π`. -/
noncomputable def integralMinimalPolynomial {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (c : C) : (TateAlgebra K (Fin n))[X] :=
  letI : Algebra (TateAlgebra K (Fin n)) C := π.toRingHom.toAlgebra
  minpoly (TateAlgebra K (Fin n)) c

/-- Finiteness makes the integral minimal polynomial monic. -/
theorem integralMinimalPolynomial_monic {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπfinite : π.Finite) (c : C) :
    (integralMinimalPolynomial K π c).Monic := by
  let A := TateAlgebra K (Fin n)
  letI : Algebra A C := π.toRingHom.toAlgebra
  letI : Module.Finite A C := hπfinite
  change (minpoly A c).Monic
  exact minpoly.monic (IsIntegral.of_finite A c)

/-- The integral minimal polynomial annihilates the original element. -/
theorem eval₂_integralMinimalPolynomial {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (c : C) :
    Polynomial.eval₂ π.toRingHom c (integralMinimalPolynomial K π c) = 0 := by
  let A := TateAlgebra K (Fin n)
  letI : Algebra A C := π.toRingHom.toAlgebra
  change Polynomial.eval₂ (algebraMap A C) c (minpoly A c) = 0
  simpa only [Polynomial.aeval_def] using minpoly.aeval A c

/-- Lemma 4.5.5 over an integrally closed base: the integral minimal polynomial becomes the field
minimal polynomial after passing to fraction fields. -/
theorem isFractionMinpoly_integralMinimalPolynomial [IsDomain C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπinj : Function.Injective π)
    (hπfinite : π.Finite) (c : C) :
    IsFractionMinpoly K π hπinj c (integralMinimalPolynomial K π c) := by
  let A := TateAlgebra K (Fin n)
  letI : Algebra A C := π.toRingHom.toAlgebra
  letI : FaithfulSMul A C :=
    (faithfulSMul_iff_algebraMap_injective A C).mpr hπinj
  letI : Module.Finite A C := hπfinite
  letI : Algebra (FractionRing A) (FractionRing C) :=
    FractionRing.liftAlgebra A (FractionRing C)
  letI : IsScalarTower A (FractionRing A) (FractionRing C) :=
    FractionRing.isScalarTower_liftAlgebra A (FractionRing C)
  change (minpoly A c).map (algebraMap A (FractionRing A)) =
    minpoly (FractionRing A) (algebraMap C (FractionRing C) c)
  exact (minpoly.isIntegrallyClosed_eq_field_fractions
    (R := A) (S := C) (FractionRing A) (FractionRing C) (IsIntegral.of_finite A c)).symm

/-- A relation identified with the fraction-field minimal polynomial annihilates the maximal
Gauss root. -/
theorem hasFractionMinpolyGaussRoot_of_isFractionMinpoly [IsDomain C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπinj : Function.Injective π) (c : C)
    {P : (TateAlgebra K (Fin n))[X]} (hP : P.Monic) (hPdeg : 0 < P.natDegree)
    (hmin : IsFractionMinpoly K π hπinj c P) :
    HasFractionMinpolyGaussRoot K π hπinj c hP hPdeg := by
  let A := TateAlgebra K (Fin n)
  let L := GaussAlgebraicClosure K n
  letI : Algebra A C := π.toRingHom.toAlgebra
  letI : FaithfulSMul A C :=
    (faithfulSMul_iff_algebraMap_injective A C).mpr hπinj
  letI : Algebra A L := (gaussAlgebraicClosureMap K n).toAlgebra
  letI : FaithfulSMul A L :=
    (faithfulSMul_iff_algebraMap_injective A L).mpr
      (gaussAlgebraicClosureMap_injective K n)
  letI : Algebra (FractionRing A) (FractionRing C) :=
    FractionRing.liftAlgebra A (FractionRing C)
  change P.map (algebraMap A (FractionRing A)) =
    minpoly (FractionRing A) (algebraMap C (FractionRing C) c) at hmin
  change Polynomial.eval₂ (IsFractionRing.lift (gaussAlgebraicClosureMap_injective K n))
    (gaussMaxRoot K hP hPdeg)
      (minpoly (FractionRing A) (algebraMap C (FractionRing C) c)) = 0
  have hcomp :
      (IsFractionRing.lift (gaussAlgebraicClosureMap_injective K n)).comp
        (algebraMap A (FractionRing A)) = gaussAlgebraicClosureMap K n := by
    ext a
    exact IsFractionRing.lift_algebraMap (A := A) (K := FractionRing A) (L := L)
      (g := gaussAlgebraicClosureMap K n) (gaussAlgebraicClosureMap_injective K n) a
  rw [← hmin, Polynomial.eval₂_map, hcomp]
  exact eval₂_gaussMaxRoot K hP hPdeg

/-- Once the fraction-field minimal-polynomial identity is known, the Gauss-root functional is
automatic: extend evaluation linearly and apply the finite-module open-mapping theorem. -/
theorem hasBoundedGaussMaxRootFunctional_of_fractionMinpolyRoot [IsDomain C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπinj : Function.Injective π)
    (hπfinite : π.Finite) (hπcont : Continuous π) (c : C)
    {P : (TateAlgebra K (Fin n))[X]} (hP : P.Monic) (hPdeg : 0 < P.natDegree)
    (hroot : HasFractionMinpolyGaussRoot K π hπinj c hP hPdeg) :
    HasBoundedGaussMaxRootFunctional K c hP hPdeg := by
  let A := TateAlgebra K (Fin n)
  let H := GaussResidueField K n
  let L := GaussAlgebraicClosure K n
  letI : NormedField L := spectralNorm.normedField H L
  letI : NormedAlgebra H L := spectralNorm.normedAlgebra H L
  letI : NormedAlgebra K L := NormedAlgebra.restrictScalars K H L
  letI : Algebra A C := π.toRingHom.toAlgebra
  letI : IsScalarTower K A C := IsScalarTower.of_algebraMap_eq fun r ↦ (π.commutes r).symm
  letI : ContinuousSMul A C :=
    continuousSMul_of_continuousRingHom π.toRingHom hπcont
  letI : FaithfulSMul A C :=
    (faithfulSMul_iff_algebraMap_injective A C).mpr hπinj
  letI : Module.Finite A C := hπfinite
  let ι : A →ₐ[K] L :=
    { __ := gaussAlgebraicClosureMap K n
      commutes' := fun _ ↦ rfl }
  letI : Algebra A L := (gaussAlgebraicClosureMap K n).toAlgebra
  let hKAL : IsScalarTower K A L :=
    IsScalarTower.of_algebraMap_eq fun r ↦ (ι.commutes r).symm
  letI : IsScalarTower K A L := hKAL
  have hιnorm (a : A) : ‖ι a‖ = ‖a‖ :=
    spectralNorm_gaussAlgebraicClosureMap K n a
  have hιcont : Continuous ι :=
    (AddMonoidHomClass.isometry_of_norm ι hιnorm).continuous
  letI : ContinuousSMul A L :=
    continuousSMul_of_continuousRingHom (gaussAlgebraicClosureMap K n) hιcont
  letI : FaithfulSMul A L :=
    (faithfulSMul_iff_algebraMap_injective A L).mpr
      (gaussAlgebraicClosureMap_injective K n)
  have hroot' :
      letI : Algebra (FractionRing A) (FractionRing C) :=
        FractionRing.liftAlgebra A (FractionRing C)
      Polynomial.eval₂ (IsFractionRing.lift (FaithfulSMul.algebraMap_injective A L))
        (gaussMaxRoot K hP hPdeg)
        (minpoly (FractionRing A) (algebraMap C (FractionRing C) c)) = 0 := by
    simpa only [HasFractionMinpolyGaussRoot] using hroot
  obtain ⟨G, M, hM, hGpow, hG⟩ :=
    exists_bounded_fractionRingFunctional_of_minpoly_root_of_finite
      (K := K) (A := A) (C := C) (L := L) hKAL c
      (gaussMaxRoot K hP hPdeg) hroot'
  exact ⟨G, M, hM, hGpow, hG⟩

/-- A bounded functional for the chosen maximal root packages the bounded root realization. -/
theorem hasBoundedGaussRootRealization_of_maxRootFunctional {n : ℕ} (c : C)
    {P : (TateAlgebra K (Fin n))[X]} (hP : P.Monic) (hPdeg : 0 < P.natDegree)
    (hF : HasBoundedGaussMaxRootFunctional K c hP hPdeg) :
    HasBoundedGaussRootRealization K n c P := by
  obtain ⟨F, M, hM, hFpow, hFbound⟩ := hF
  exact ⟨gaussMaxRoot K hP hPdeg, aeval_gaussMaxRoot K hP hPdeg,
    spectralNorm_gaussMaxRoot K hP hPdeg, F, M, hM, hFpow, hFbound⟩

/-- A bounded Gauss-root realization supplies the difficult inequality in Proposition 4.5.7. -/
theorem spectralValue_le_spectralRadius_of_boundedGaussRootRealization [Nontrivial C]
    {n : ℕ} (c : C) {P : (TateAlgebra K (Fin n))[X]}
    (h : HasBoundedGaussRootRealization K n c P) :
    spectralValue P ≤ BerkovichSpectrum.spectralRadius C c := by
  obtain ⟨z, -, hz, F, M, hM, hFpow, hF⟩ := h
  let H := GaussResidueField K n
  let L := GaussAlgebraicClosure K n
  letI : NormedField L := spectralNorm.normedField H L
  have hbound (a : C) : ‖F a‖ ≤ M * ‖a‖ := hF a
  rw [← hz]
  exact norm_le_spectralRadius_of_bounded_power_realization c z F M hM hFpow hbound

/-- Any continuous monic Tate-algebra relation gives the standard upper bound
`ρ(c) ≤ σ(P)`.  The proof evaluates at a Berkovich point attaining the spectral radius, passes to
its completed residue field, and applies Mathlib's nonarchimedean root bound there.  Continuity is
enough because pulling the point back along the normalization map is automatically bounded by the
Gauss norm. -/
theorem spectralRadius_le_spectralValue_of_relation [Nontrivial C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπ : Continuous π)
    (c : C) {P : (TateAlgebra K (Fin n))[X]} (hPmonic : P.Monic)
    (hPeval : Polynomial.eval₂ π.toRingHom c P = 0) :
    BerkovichSpectrum.spectralRadius C c ≤ spectralValue P := by
  obtain ⟨y, hy⟩ := BerkovichSpectrumOver.exists_apply_eq_spectralRadius K C c
  let H := BerkovichSpectrumOver.CompletedResidueField y
  let πcont : ContinuousAlgHom K (TateAlgebra K (Fin n)) C :=
    { toAlgHom := π, cont := hπ }
  let φ : TateAlgebra K (Fin n) →+* H :=
    (BerkovichSpectrumOver.completedResidueMap y).comp π.toRingHom
  let z : H := BerkovichSpectrumOver.completedResidueMap y c
  have hφ (a : TateAlgebra K (Fin n)) : ‖φ a‖ ≤ ‖a‖ := by
    change ‖BerkovichSpectrumOver.completedResidueMap y (π a)‖ ≤ ‖a‖
    rw [BerkovichSpectrumOver.norm_completedResidueMap]
    exact BerkovichSpectrumOver.le_norm K _ 
      (BerkovichSpectrumOver.comapContinuous K _ πcont y) a
  have hz : Polynomial.aeval z (P.map φ) = 0 := by
    have hmap := congrArg (BerkovichSpectrumOver.completedResidueMap y) hPeval
    rw [map_zero, Polynomial.hom_eval₂] at hmap
    simpa only [Polynomial.aeval_def, Polynomial.eval₂_map, Algebra.algebraMap_self,
      RingHom.id_comp] using hmap
  let ν : AlgebraNorm H H :=
    { toFun := norm
      map_zero' := norm_zero
      add_le' := norm_add_le
      neg' := norm_neg
      smul' := norm_mul
      mul_le' := norm_mul_le
      eq_zero_of_map_eq_zero' := fun _ h ↦ norm_eq_zero.mp h }
  have hνpow : IsPowMul ν := by
    intro x m _
    change ‖x ^ m‖ = ‖x‖ ^ m
    exact norm_pow x m
  have hνna : IsNonarchimedean ν := by
    intro x x'
    change ‖x + x'‖ ≤ max ‖x‖ ‖x'‖
    exact IsUltrametricDist.norm_add_le_max x x'
  have hroot : ‖z‖ ≤ spectralValue (P.map φ) := by
    have hνz : ν z = ‖z‖ := rfl
    rw [← hνz]
    exact norm_root_le_spectralValue (f := ν) hνpow hνna (hPmonic.map φ) hz
  calc
    BerkovichSpectrum.spectralRadius C c = y c := hy.symm
    _ = ‖z‖ := (BerkovichSpectrumOver.norm_completedResidueMap y c).symm
    _ ≤ spectralValue (P.map φ) := hroot
    _ ≤ spectralValue P := spectralValue_map_le φ hφ hPmonic

/-- The sharp polynomial supplied by Proposition 4.5.3 for a Noether-normalizing Tate algebra. -/
def HasSharpSpectralPolynomial (n : ℕ) (π : TateAlgebra K (Fin n) →ₐ[K] C)
    (c : C) : Prop :=
  ∃ P : (TateAlgebra K (Fin n))[X], P.Monic ∧ Polynomial.eval₂ π.toRingHom c P = 0 ∧
    BerkovichSpectrum.spectralRadius C c = spectralValue P

/-- Proposition 4.5.7 reduced to its finite-module functional: the usual root bound gives one
inequality, while a bounded realization of the maximal Gauss root gives the other. -/
theorem hasSharpSpectralPolynomial_of_boundedGaussRootRealization [Nontrivial C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπ : Continuous π)
    (c : C) {P : (TateAlgebra K (Fin n))[X]} (hPmonic : P.Monic)
    (hPeval : Polynomial.eval₂ π.toRingHom c P = 0)
    (hroot : HasBoundedGaussRootRealization K n c P) :
    HasSharpSpectralPolynomial K n π c := by
  refine ⟨P, hPmonic, hPeval, le_antisymm
    (spectralRadius_le_spectralValue_of_relation K π hπ c hPmonic hPeval) ?_⟩
  exact spectralValue_le_spectralRadius_of_boundedGaussRootRealization K c hroot

/-- Domain-case Proposition 4.5.7 with only its final bounded-functional input exposed. -/
theorem hasSharpSpectralPolynomial_of_maxRootFunctional [Nontrivial C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπ : Continuous π)
    (c : C) {P : (TateAlgebra K (Fin n))[X]} (hPmonic : P.Monic)
    (hPeval : Polynomial.eval₂ π.toRingHom c P = 0)
    (hF : HasBoundedGaussMaxRootFunctional K c hPmonic
      (natDegree_pos_of_monic_relation K π.toRingHom c hPmonic hPeval)) :
    HasSharpSpectralPolynomial K n π c := by
  apply hasSharpSpectralPolynomial_of_boundedGaussRootRealization K π hπ c hPmonic hPeval
  exact hasBoundedGaussRootRealization_of_maxRootFunctional K c hPmonic
    (natDegree_pos_of_monic_relation K π.toRingHom c hPmonic hPeval) hF

/-- Domain-case Proposition 4.5.7, reduced exactly to Lemma 4.5.5: a monic relation that becomes
the fraction-field minimal polynomial has spectral value equal to the spectral radius. -/
theorem hasSharpSpectralPolynomial_of_isFractionMinpoly [IsDomain C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C)
    (hπinj : Function.Injective π) (hπfinite : π.Finite) (hπcont : Continuous π)
    (c : C) {P : (TateAlgebra K (Fin n))[X]} (hPmonic : P.Monic)
    (hPeval : Polynomial.eval₂ π.toRingHom c P = 0)
    (hmin : IsFractionMinpoly K π hπinj c P) :
    HasSharpSpectralPolynomial K n π c := by
  let hPdeg := natDegree_pos_of_monic_relation K π.toRingHom c hPmonic hPeval
  apply hasSharpSpectralPolynomial_of_maxRootFunctional K π hπcont c hPmonic hPeval
  apply hasBoundedGaussMaxRootFunctional_of_fractionMinpolyRoot K π hπinj
    hπfinite hπcont c hPmonic hPdeg
  exact hasFractionMinpolyGaussRoot_of_isFractionMinpoly K π hπinj c hPmonic hPdeg hmin

/-- Proposition 4.5.7 over a Noether-normalizing Tate algebra.  The integrally-closed input is
supplied by the Rückert unique-factorization induction. -/
theorem hasSharpSpectralPolynomial_of_integrallyClosedNormalization [IsDomain C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C)
    (hπinj : Function.Injective π) (hπfinite : π.Finite) (hπcont : Continuous π)
    (c : C) : HasSharpSpectralPolynomial K n π c := by
  apply hasSharpSpectralPolynomial_of_isFractionMinpoly K π hπinj hπfinite hπcont c
    (integralMinimalPolynomial_monic K π hπfinite c)
    (eval₂_integralMinimalPolynomial K π c)
  exact isFractionMinpoly_integralMinimalPolynomial K π hπinj hπfinite c

/-- The precise output of the missing finite-fiber argument in Proposition 4.5.7: a point above
the Gauss point at which the chosen root has size `σ(P)`. -/
def HasGaussFiberMaximum {n : ℕ} (π : TateAlgebra K (Fin n) →ₐ[K] C) (c : C)
    (P : (TateAlgebra K (Fin n))[X]) : Prop :=
  ∃ y : BerkovichSpectrumOver K C,
    (∀ a, y (π a) = ‖a‖) ∧ y c = spectralValue P

/-- The standard upper bound together with the finite-fiber maximum gives the sharp equality of
Proposition 4.5.7. -/
theorem hasSharpSpectralPolynomial_of_gaussFiberMaximum [Nontrivial C] {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπ : Continuous π)
    (c : C) {P : (TateAlgebra K (Fin n))[X]} (hPmonic : P.Monic)
    (hPeval : Polynomial.eval₂ π.toRingHom c P = 0)
    (hfiber : HasGaussFiberMaximum K π c P) : HasSharpSpectralPolynomial K n π c := by
  refine ⟨P, hPmonic, hPeval, le_antisymm
    (spectralRadius_le_spectralValue_of_relation K π hπ c hPmonic hPeval) ?_⟩
  obtain ⟨y, -, hy⟩ := hfiber
  rw [← hy]
  exact BerkovichSpectrumOver.le_spectralRadius K C y c

/-- A sharp spectral polynomial for an element in the closed spectral unit ball has all its
coefficients in the Gauss unit ball. -/
theorem hasUnitBallRelation_of_hasSharpSpectralPolynomial {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (c : C)
    (hc : BerkovichSpectrum.spectralRadius C c ≤ 1)
    (hsharp : HasSharpSpectralPolynomial K n π c) :
    HasUnitBallRelation K n π.toRingHom c := by
  obtain ⟨P, hPmonic, hPeval, hsharp⟩ := hsharp
  refine ⟨P, hPmonic, ?_, hPeval⟩
  intro i
  change ‖P.coeff i‖ ≤ 1
  apply norm_coeff_le_one_of_spectralValue_le_one hPmonic
  rwa [← hsharp]

/-- Proposition 4.5.3 immediately supplies the certificate used in Proposition 4.5.12. -/
theorem hasUnitBallIntegralCertificate_of_hasSharpSpectralPolynomial {n : ℕ}
    (π : TateAlgebra K (Fin n) →ₐ[K] C) (hπ : Continuous π) (c : C)
    (hc : BerkovichSpectrum.spectralRadius C c ≤ 1)
    (hsharp : HasSharpSpectralPolynomial K n π c) :
    HasUnitBallIntegralCertificate K c := by
  let πcont : ContinuousAlgHom K (TateAlgebra K (Fin n)) C :=
    { toAlgHom := π, cont := hπ }
  exact ⟨n, πcont, isIntegral_image_unitBall_of_hasUnitBallRelation K n π.toRingHom c
    (hasUnitBallRelation_of_hasSharpSpectralPolynomial K π c hc hsharp)⟩

/-- A Noether normalization together with Proposition 4.5.3 for every element.  The finite
injective map is already supplied algebraically by Noether normalization; continuity and the
sharp polynomial are the remaining analytic inputs. -/
def HasSharpNoetherNormalization (C : Type v) [NormedCommRing C] [NormedAlgebra K C] : Prop :=
  ∃ (n : ℕ) (π : TateAlgebra K (Fin n) →ₐ[K] C),
    Function.Injective π ∧ π.Finite ∧ Continuous π ∧
      ∀ c : C, HasSharpSpectralPolynomial K n π c

/-- In the domain case, Noether normalization and continuity of the normalizing map supply all
the sharp spectral polynomials of Proposition 4.5.7. -/
theorem hasSharpNoetherNormalization_of_isAffinoidAlgebra_of_isDomain [IsDomain C]
    (hC : IsAffinoidAlgebra K C)
    (hcontinuous : ∀ {n : ℕ} (π : TateAlgebra K (Fin n) →ₐ[K] C), Continuous π) :
    HasSharpNoetherNormalization K C := by
  obtain ⟨n, π, hπinj, hπfinite⟩ :=
    exists_finite_injective_tateAlgebra_of_isAffinoidAlgebra K hC
  have hπcont : Continuous π := hcontinuous π
  exact ⟨n, π, hπinj, hπfinite, hπcont,
    hasSharpSpectralPolynomial_of_integrallyClosedNormalization K π
      hπinj hπfinite hπcont⟩

/-- Sharp spectral polynomials over one Noether normalization imply the boundary case in the
power-boundedness criterion. -/
theorem hasPowerBoundedSpectralCriterion_of_hasSharpNoetherNormalization [Nontrivial C]
    (hC : HasSharpNoetherNormalization K C) : HasPowerBoundedSpectralCriterion C := by
  apply hasPowerBoundedSpectralCriterion_of_certificates K
  intro c hc
  obtain ⟨n, π, -, -, hπ, hsharp⟩ := hC
  exact hasUnitBallIntegralCertificate_of_hasSharpSpectralPolynomial K π hπ c hc (hsharp c)

/-- The non-domain form of Proposition 4.5.3 reduced to its componentwise input.  All minimal
prime components must use one continuous Tate-algebra coefficient map; the algebraic
minimal-prime argument then removes the nilpotent error. -/
theorem hasPowerBoundedSpectralCriterion_of_minimalPrime_relations
    [Nontrivial C] [IsNoetherianRing C] {n : ℕ}
    (π : ContinuousAlgHom K (TateAlgebra K (Fin n)) C)
    (hrelations : ∀ c : C, BerkovichSpectrum.spectralRadius C c ≤ 1 →
      ∀ q ∈ minimalPrimes C,
        HasUnitBallRelation K n ((Ideal.Quotient.mk q).comp π.toRingHom)
          (Ideal.Quotient.mk q c)) :
    HasPowerBoundedSpectralCriterion C := by
  apply hasPowerBoundedSpectralCriterion_of_certificates K
  intro c hc
  exact hasUnitBallIntegralCertificate_of_minimalPrime_quotients K π c
    (hrelations c hc)

/-- Proposition 4.5.12 for an affinoid domain, with automatic continuity of its normalizing maps
left as an explicit topological input. -/
theorem hasPowerBoundedSpectralCriterion_of_isAffinoidAlgebra_of_isDomain [IsDomain C]
    (hC : IsAffinoidAlgebra K C)
    (hcontinuous : ∀ {n : ℕ} (π : TateAlgebra K (Fin n) →ₐ[K] C), Continuous π) :
    HasPowerBoundedSpectralCriterion C :=
  hasPowerBoundedSpectralCriterion_of_hasSharpNoetherNormalization K
    (hasSharpNoetherNormalization_of_isAffinoidAlgebra_of_isDomain K hC hcontinuous)

end Tate

end SpectralPolynomial

end Rigid
